### ISSUE TITLE
Performance decrease in Kirby 3.6.0-rc.1

### ISSUE THREAD

**Issue by gitlabisbetterthangithub** [k-next/kirby#3825]
**Describe the bug**  
Navigating around Kirby 3.6.0-rc.1 seems slower than Kirby 3.5.7.1. I tested the performance of 3.6.0-rc.1 and 3.5.7.1 in DevTools and there is a significant difference.

**To Reproduce**  
1. Open Chrome's DevTools
2. Click on the performance tab
3. Press the reload button or Ctrl + Shift + E
4. Repeat the steps in 3.5.7.1 and compare the difference

**Expected behavior**  
Performance should be similar to Kirby 3.5.7.1

**Screenshots**  
3.6.0-rc.1
![image](https://user-images.githubusercontent.com/40391197/138016621-bf238ca5-61da-42b9-85be-dea2b1f0c25a.png)
3.5.7.1
![image](https://user-images.githubusercontent.com/40391197/138016672-fed81c34-9685-40c9-bd4a-c1ad0c157b44.png)

**Kirby Version**  
Kirby 3.6.0-rc.1

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - Browser: Chrome
 - Version: 94

**Comment by bastianallgeier** [comment]
Are those performance changes affecting your site or the panel? I think we need to have a closer look at your project to find out what's happening.

**Comment by bastianallgeier** [comment]
Just a thought. In 3.6 we had to change the file names for cropped images. This means that all cropped thumbnails have to be regenerated once. This could easily cause such a performance drop on the first few requests. Did you check what happens after repeated requests?

**Comment by gitlabisbetterthangithub** [comment]
@bastianallgeier This is the Panel. I've cleared the media folder and tried it again and got a more acceptable result of 1796ms. I think the perceived performance has decreased and that's why I feel like it's slower than in 3.5.7.1 which might be because 3.6 is no longer a single page application.

I am using performance in DevTools to measure it so you had something to go off but I might be using the performance tools wrong. It's probably not worth investigating.

**Comment by bastianallgeier** [comment]
It's interesting because we got quite a bit of feedback telling us that the perceived performance is faster now in 3.6. I think it's very subjective what actually feels faster to every individual user. With the single page application, routing started immediately after the click and elements would already disappear from the view before the new content even finished loading. This might seem faster to some users because the visual effect is a bit stronger. But in our tests, our new setup is completing a lot faster. We could emulate the same vanishing effect on click to get back that snappiness. But so far we all agreed that the new way of routing feels more solid and has major advantages in terms of layout shifts and other weird side effects.
