### ISSUE TITLE
Disable cache on active sessions only

### ISSUE THREAD

**Issue by sebastiangreger** [k-next/kirby#3976]
Following up from a long discussion over at https://discord.com/channels/525634039965679616/525641819854471168/914572838143393792

PR #3292 introduced a new rule in 3.5.5 where any call to the `kirby()->session()` method apparently disables the page cache and sends a "absolutely no caching" header to user agents.

As presented in the Discord discussion, this apparently will be triggered by code that merely checks whether a session is present or not – essentially disabling page cache and browser cache for any page that for instance checks for `if(kirby()->user())`, even if there is no active session. This also creates a risk of inadvertently disabling caching by installing a third-party plugin that uses such check somewhere.

Could this rule be "tuned down" by only applying these rules when an active session exists (as the title of the PR indicated "Disable cache on **active** sessions"), rather than triggering it already by the check for an active session? Without deeper knowledge of the considerations that led to this change, it seems that no critical content should be ending up in cache if the rendered page is the "public version" in the first place?

CC @bvdputte

**Comment by bastianallgeier** [comment]
@lukasbestle as mentioned on Discord, I think you should have a look at this.

**Comment by lukasbestle** [comment]
There are four cases to consider:

**Active session, response is cached**

This case is obviously critical as private data may be leaked to other visitors.

**Active session, response is *not* cached**

Perfect ✅

**No active session, response is cached**

Not critical from a security perspective, but could lead to bugs where a logged in user gets a "public" page from cache instead of the personalized one.

This is why I decided to base the caching decision just on whether the session is used at all (which tells that the response will differ if a session is active).

**No active session, response is *not* cached**

This is what you describe. Would be nice to avoid but IMO can't be due to the reasons mentioned above.

**Comment by lukasbestle** [comment]
What we could do is to send the `Vary: Cookie` header to tell caches that the response differs for users with session. But I'm not sure if all caches respect that fully.

**Comment by lukasbestle** [comment]
Regarding Kirby's page cache: Right now Kirby will always use the cache, even if a user is logged in. What we could do there is to add a flag to the cache value that it may only be used if no session is active. Then everything would work automagically again.

Back then it really was an emergency, so we had to get it out the door quickly and didn't fully realize the implications for plugin devs.

**Comment by sebastiangreger** [comment]
Thanks for sharing the thought process behind this implementation – that is all 100% comprehensible and a really tricky challenge, not least because this mixes two things: the server-side page cache and the policy header for user agent caching.

This one was an eye-opener in particular:

> Not critical from a security perspective, but could lead to bugs where a logged in user gets a "public" page from cache instead of the personalized one.

So – given that the statements for the security-critical scenarios are undisputedly valid – the reason for the "overbearing" ban on caching for any page that even checks the session primarily stems from the need to avoid this scenario:

- a user visits the publicly available version of a page
- browser puts that into cache
- user logs in and returns to that page
- browser deals out the cached page instead of the "logged-in" version

(Essentially the same issue in reverse where the first visit is as logged-in user, but if we were to deal with "session plus logged-in" as a security risk that leads to ban on caching this would be solved by sending out the internal versions with "no caching" headers?)

**Thought No 1: Disabling the server-side page cache for logged-in users (either by default or configurable) while restoring it for any non-authenticated requests even if a session condition exists**

The page cache (`$kirby->response()->cache()`) is not really affected by this scenario at all. The non-logged-in "public" version could still be cached in the page cache and provided for the (assumed, on most websites) majority of traffic. This would solve the desire to not completely disable the server-side cache, with all its potential impact on performance etc.

If as per your suggestion…

> Regarding Kirby's page cache: Right now Kirby will always use the cache, even if a user is logged in. What we could do there is to add a flag to the cache value that it may only be used if no session is active. Then everything would work automagically again.

…this is possible to be done (something I [hacked into config earlier](https://getkirby.com/docs/cookbook/setup/selective-page-cache), though this, admittedly, too may lead to the usability issue with the browser cache you raise above), that would remove the entire page cache complex from the more intricate challenge of the user agent caching?

**Thought No 2: Making the UA headers sent out in different scenarios configurable (with yet-to-be-determined defaults that address security concerns while maintaining good UX)**

The UA cache headers aspect is a lot more difficult. Unfortunately, support for the `Vary` header (great feature!) seems [to be abysmal](https://caniuse.com/mdn-http_headers_vary), so that's not going to solve this for years to come.

The frontend caching question maybe boils down to what hard defaults Kirby as a CMS wants to set, and what is optional or at least configurable?

To provide two real-world user stories:

1. I want to be able to employ a `router:after` hook for a small pageview counter script that excludes the hundreds of page views by editorial staff: it's called on every page call, even though admins are served the 1:1 identical HTML as public users and I would like to use my carefully optimized configuration of frontend cache headers.

2. I want to be able to offer a plugin that embeds an accessibility checker tool for all page views by logged in editors (`kirby()->user()` checked in a snippet) that every Kirby admin can install without worries about it affecting their caching rules.

Maybe the problem with the frontend headers is more one of a too strict (and, as far as I can see not easily configurable) default than one of security? While I'd assume my CMS to ensure the security part (i.e. "no cache" header for pages with session and a logged-in user), I would personally prefer to be able to control the UX part myself (e.g. on a site where the use of session checks does not affect the frontend code at all).

**Comment by lukasbestle** [comment]
Thanks for sharing your thoughts and your detailed reply.

> - a user visits the publicly available version of a page
> - browser puts that into cache

Not just the browser actually but also intermediary caches like Varnish (common on many shared hosting servers) or forward proxy servers (common in business environments). These caches affect all users, so it would be enough that anyone visits the public page before the logged in user does.

The `Vary` header is mostly meant for such intermediary caches which should ideally support it (it's their main job to do proper caching after all). But I'm not 100% sure.

IMO we could still go the automatic `Vary` route as it avoids even more configuration options to take care of. I think configuration would be more confusing than helpful.

And if browsers really don't support `Vary` ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary) says they do), the cache can still be cleared manually if there are any issues (which is unlikely as we haven't seen issues before the cache block in 3.5.5).

I suggest the following:

**Session is not used (no matter if active or not):**

Kirby caches the page as normal.

**Session is used, but not active:**

- Page cache gets a flag that tells Kirby to only use the cached value for non-active sessions.
- Kirby sends the `Vary: Authorization, Cookie` header.

**Session is used and active:**

- Page cache is completely disabled (both storing and retrieving).
- The cache-blocking header is sent.

**Comment by sebastiangreger** [comment]
@lukasbestle that looks like a brilliant solution that should not only solve this, but actually significantly improve the page cache! …and you are of course absolutely right, caniuse is obviously wrong about the `Vary` support – all other sources I assessed, e.g. [here](https://www.mnot.net/blog/2017/03/16/browser-caching#vary), indicate this has been working for ages, on browsers and intermediate caches alike.

I ran a few crosschecks of your proposal with the user stories surfaced during this discussion:

**A) As a site owner I want to display sensitive data to logged-in users that shall never end up in any cache** (the "emergency case" from earlier this year)

* User is logged in, accesses page that presents sensitive data for logged-in users:
  * page cache disabled, data does not end up in page cache :heavy_check_mark:
  * no-cache headers sent, receiving end advised not to cache under any circumstances :heavy_check_mark:
* User is not logged in, accesses page that presents sensitive data for logged-in users:
  * no sensitive data involved, because not logged in :heavy_check_mark:
  * copy created in or served from page cache won't contain sensitive data :heavy_check_mark:
  * `Vary` header ensures display of personalized version after cookie changes on login :heavy_check_mark:

This security-critical case should be covered.

**B) As a developer, I want to use `kirby()->user()` in a `route:after` hook for a page counter that does not affect the frontend output at all.** (my example of a page counter excluding admin pageviews)

* User is not logged in:
  * Page cache serves (or creates) a stored "public" version :heavy_check_mark:
  * Server sends `Vary` header that will enforce retrieval of fresh version after session cookie is set :heavy_check_mark:
* User is logged in:
  * Page cache disabled for all pages on website (due to the hook being triggered always), every page is rendered fresh :white_check_mark:
  * Server sends no-cache header for all pages :white_check_mark:

For this scenario, the (assumedly most common) "public" user gets the full benefit of both caches while `Vary` ensures that they get a fresh version after login. Only "side effect" (hence the :white_check_mark: icons) is that users with an active session do not benefit from either cache; this is probably unavoidable, could only be performance-relevant on sites that rely broadly on users with active sessions.

**C) As a plugin author I want to provide a snippet that embeds a piece of frontend code for admin users** (the example of my a11yprompter plugin) and – identical scenario – **as developer I want to provide a "Edit page" button for logged-in users on the frontend** (the case that started the Discord discussion).

* User is not logged in:
  * Page cache serves (or creates) a stored "public" version :heavy_check_mark:
  * Server sends `Vary` header that will enforce retrieval of fresh version after session cookie is set :heavy_check_mark:
* User is logged in:
  * Page cache disabled, pages that carry the snippet or display that button are rendered on every request :heavy_check_mark:
  * Frontend code aimed at editors will not end up in page cache :heavy_check_mark:
  * Server sends no-cache header for the pages using the snippet/button, ensuring the admin-specific elements are no longer shown after logout :heavy_check_mark:

As the previous scenario: full performance benefit for users without active session, no caching whatsoever for the logged-in users. Here, the "performance tax" only affects those pages that check for a session, so a less global impact than the hook scenario.

:arrow_right: The solution seems to indeed "dial back" the ban on caching while maintaining security for sensitive data; the only sites that would still be affected would be sites that have massive traffic of users with active sessions (where I actually just realized this not only includes logged-in users but would probably also affect sites that f.ex. protect forms with CSRF tokens, correct?)

Did I overlook anything?

**Comment by lukasbestle** [comment]
All looks correct.

Yes, also pages with CSRF token checks are affected as they use the session. I wouldn't differentiate between user sessions and other session values. After all any page that uses the cache is dynamic and shares the same issues.

The question is just what happens with the page where the CSRF token is first created. If a user visits this page without an active session, they will get the page from cache and the code that creates the session will not be run at all. Is there a way to avoid this?

**Comment by sebastiangreger** [comment]
> After all any page that uses the cache is dynamic and shares the same issues.

Absolutely. We wouldn't want to have invalid CSRF tokens in the cache either.

This probably is just something that should be present in the documentation somewhere. Along the lines of "note that creating a CSRF token will disable Kirby's page cache and send out a "no cache" headers with the response".

> If a user visits this page without an active session, they will get the page from cache and the code that creates the session will not be run at all. Is there a way to avoid this?

Without deeper understanding of the technical architecture: would it be possible to trigger the same logic from your proposal not only when a session is **used and active**, but also when it is **created**? E.g. when a CSRF token is generated? Or are we opening a can of worms there?

**Comment by lukasbestle** [comment]
If a page always creates a session that would already work as creating the session means at the same time that the session is accessed. The issue is just that the page gets cached if the session is only created with a special query string or other kinds of conditional logic.

But now that I think about it: We already have the `cache.ignore` option for this that allows to prevent caching in these cases. So I think there's nothing special to keep in mind.

@bastianallgeier @distantnative I'd add this to the 3.6.2 milestone. What do you think?
The summary of changes is here: https://github.com/getkirby/kirby/issues/3976#issuecomment-982328147

**Comment by lukasbestle** [comment]
@bastianallgeier @distantnative Ping regarding my roadmap suggestion

**Comment by lukasbestle** [comment]
# 👷 Proposed change

## Status quo

When `$kirby->session()` is called, Kirby [disables both the page cache and intermediate/browser caches](https://github.com/getkirby/kirby/blob/3.6.1.1/src/Cms/App.php#L1276-L1278). This was done for security reasons to avoid that pages with private information are cached and served to other users.

## Why is it problematic

The feature completely blocks caching even for public responses (when no user is logged in). This makes caching useless on sites that display additional information for logged in users.

## Proposed solution

The core should be a bit more clever about the session. It should not only take into account whether the session is used (as before: `$kirby->session()` is called) but also whether the session is active (= whether the session contains any value like user or CSRF token):

**Session is not used (no matter if active or not):**

Kirby caches the page as normal.

**Session is used, but not active:**

- Page cache gets a flag that tells Kirby to only use the cached value for non-active sessions.
- Kirby sends the `Vary: Authorization, Cookie` header so that intermediary caches know to serve dynamic content to users with session.

**Session is used and active:**

- Page cache is completely disabled (both storing and retrieving).
- Kirby sends the `Cache-Control: no-store` header.

## Limitation

Cannot catch pages that only sometimes use or create a session. If the page gets rendered without using the session, it will get cached and will never be able to run the session code. For that the dev still needs to set the `cache.ignore` option. We should document this case explicitly (which should be the only one where `cache.ignore` is necessary from now).

## Anticipated side effects

None

## Estimated impact

- The `Cms\Responder::$cache` property needs a new value for the special non-active session mode.
- The `Cache` package needs to store that flag for every cache value. Maybe it makes sense to support an associative array with arbitrary custom meta information to make the feature more flexible (the "non-active session mode" in particular only makes sense for the page cache). We can later use this meta array for the YAML hash for example.
- `$page->render()` needs to check the flag and only use the cache if it is not set or if no session is active.

---

I'd say it's moderately complex to implement and review. Not too much code, but we need to do manual tests to check if it works as expected in real life.

**Comment by sebastiangreger** [comment]
Just dropping this reference here, since questions about this surface regularly – in case it's of use to somebody else: I shared a temporary hack/workaround to check for logged-in users in the frontend without wholesale-disabling the cache: https://forum.getkirby.com/t/pages-cache-stays-empty/24820/4 …it ain't pretty, but it works and may mitigate this issue for the time being in some contexts.

**Comment by distantnative** [comment]
@lukasbestle I think the proposed change makes sense, will you set up a PR - then we can test it

**Comment by lukasbestle** [comment]
I'm working on an implementation for the plan we discussed.

Only change: Instead of basing it just on the session, I've decided to also base it on the used cookies. This covers cases like a privacy banner that stores a simple cookie if the user has accepted the banner. If the cookie is set, the response needs to be considered private. In a later version we could extend that further to cache different responses (one per possible cookie value). But in this first step, I think it already makes sense to disable the cache if the response uses cookies (no matter if session or normal cookies).

The `Authorization` header is also covered for basic auth and sessions transmitted via this header.

## New behavior

### Cookies

**The `Cookie` class is not used (no matter if the `Cookie` request header is set or not):**

Kirby caches the page as normal.

**`Cookie` class is used, but the used cookies are not set in the request or response:**

- Page cache gets the list of used cookies that tells Kirby to only use the cached value for requests that don't have these set.
- Kirby sends the `Vary: Cookie` header so that intermediary caches know to serve dynamic content to users with different cookie values.

**`Cookie` class is used and the cookies are set in the request or response:**

- Page cache is completely disabled (both storing and retrieving).
- Kirby sends the `Cache-Control: no-store` header.
- Could be extended later to cache multiple responses for each combination of cookie values.

### `Authorization` request header

**The `Authorization` header is not used (no matter if it is set or not):**

Kirby caches the page as normal.

**Page asks for the `Authorization` header, but header is not set:**

- Page cache gets the flag that tells Kirby to only use the cached value for requests that don't have the `Authorization` header set.
- Kirby sends the `Vary: Authorization` header so that intermediary caches know to serve dynamic content to users with the `Authorization` header.

**Page asks for the `Authorization` header and header is set** or
**Page uses a session in `manual` mode:**

- Page cache is completely disabled (both storing and retrieving).
- Kirby sends the `Cache-Control: no-store` header.

**Comment by bastianallgeier** [comment]
✅
