### ISSUE TITLE
Kirby Page Factory has insufficient data validation

### ISSUE THREAD

**Issue by the-leonat** [k-next/kirby#4039]
## Description
When creating virtual pages with `Pages::factory`, kirby structures can't just simply be inserted as arrays but have to be converted to yaml with `Data::encode($structure), 'yaml')`. 

This is not documented in the [virtual pages docs](https://getkirby.com/docs/guide/virtual-pages).

If nested array data is not encoded as yaml this leads to unexpected behaviour in the search function which is hard to debug and the issue difficult to locate because the error messages are not expressive enough.

After hours of searching and adding debug messages to internal kirby code I found [this post](https://forum.getkirby.com/t/createchild-structure/15688) in the forum which led me on the right track.

**Expected behavior**  
Page factory method deeply checks for nested arrays and does the yaml encoding automatically **or** logs a warning message.

Virtual pages docs are extended by a paragraph on how to create structures within virtual pages.

## Your setup
**Kirby Version**  
Latest

**Comment by afbora** [comment]
You have to send the page data in the correct format. When you load data directly on the `Page::factory()`, it is unaware of which fields it has. If you want to validate the page, you can use the `Form` class. But I'm still not sure about data type warning.

Just an example:

````php
$form = new Form([
  'fields' => $page->blueprint()->fields(),
  'model' => $page,
  'strict' => true,
  'values' => $input
]);

if ($form->errors()) {
 // throw exception
}
````

This is a enhancement suggestion rather than a bug. It can be labeled as `enhancement` or moved to Notion: https://feedback.getkirby.com/
