### ISSUE TITLE
response()->code() does not return 200 as expected

### ISSUE THREAD

**Issue by pReya** [k-next/kirby#4082]
## Description
I was meddling with the `$kirby->response()->code()` function and noticed that it does not behave as expected.

1. Create a new starterkit project
2. Create a controller for any existing template, e.g. `site/controllers/home.php`
3. Insert the following example code:
	```php
    <?php
    return function ($kirby) {
      var_dump($kirby->response()->code());
      return true;
    };
    ```
**Expected behavior**  
The value of `$kirby->response()->code()` should be `200` if the template/page was found. However it is actually `NULL`.

If you do this with a "default" controller (`site/controllers/site.php`)  and request any random non-existing page `mydomain.com/blabla`, the response code will be `404` as expected.

## Your setup
**Kirby Version**  
3.6.1

**Comment by sebastiangreger** [comment]
I have a hunch this is intended, and my message [over in the forum](https://forum.getkirby.com/t/remember-requested-path-in-session-via-default-controller/24382/5) might have mislead to seeing a bug here (I indeed do not get the `200` code either, as claimed there – I had just assumed that's what I'd get instead of a 404 for a valid page; I can replicate above behaviour).

By the time the controller is processed, Kirby probably does not yet know what response it is going to send; I'd assume the Response object is only created later, hence the `NULL`. The reason it works for 404s is probably because Kirby already knows it will return a "Not found" error by the time the default controller is executed for the error page.

Sorry again for the confusion, I should have really tested that claim of getting a `200` at that point, instead of just deducing from the error experiment… :roll_eyes:

**Comment by pReya** [comment]
Yeah, I agree. Returning a 200 would not make sense, because the controller itself could still change/modify the response. So I guess this works as expected.

**Comment by lukasbestle** [comment]
Yes, I can confirm that. The `Responder` object (`$kirby->response()`) is more of a setter than a getter from the developer perspective. Kirby only uses it to retrieve custom response metadata when it builds the final response object.
