### ISSUE TITLE
Login with timed-out code should throw user out

### ISSUE THREAD

**Issue by texnixe** [k-next/kirby#4087]
## Description
When trying to log in via code and the code has timed out, there is no way back to the login form (back button doesn't do anything) and no way to resend the code. The only way out for the user seems to be to kill the session manually.

**Expected behavior**  
There should either be a "Resend code" button or the back button should bring the user back to the login form or  the user would be redirected to the login form.

## To reproduce

1. Enable login with code in config
2. Go the `/panel/login` and request a code
3. Wait long enough for the code to time out
4. Try to log in with the timed-out code
5. See error message
6. Try the back button => nothing
7. Refresh page => you still get the form that requests the login code

## Your setup
**Kirby 3.6.1.1**  

**Your system (please complete the following information)**
 - Device: MacBook Pro (14", 2021)
 - OS: macOS 12.1
 - Browser: Firefox
 - Version: 95.0.2

**Comment by lukasbestle** [comment]
## Solution

The code that checks if the login code has expired in `Cms\Auth::verifyChallenge()` should destroy the challenge on expiry before throwing the exception. This will automatically kick the user back to the login form on the next request. Should be very simple to implement, but needs testing.

To enhance the UX, the response that destroys the challenge could already tell the frontend to render the login form component. The error message would then be displayed above the login form and the user can immediately log in again.

**Comment by bnomei** [comment]
👍 would love to see this fixed

**Comment by tmslnz** [comment]
I am experiencing this too with the latest 3.6.5 release.

**Comment by chrhuff** [comment]
This happened to one of my users immediately after I enabled code authentication. Is there any chance of getting the fix backported into a 3.6.x bugfix release?

**Comment by lukasbestle** [comment]
Unfortunately this issue didn't make it into 3.7. I will pick it up immediately after the 3.7 release.

@chrhuff We don't plan to publish additional 3.6.x releases unless we need to make a security fix. But you will be able to apply the changes from the pull request with the fix to your local installation manually.

**Comment by chrhuff** [comment]
@lukasbestle I was just hoping the issue would get solved earlier if it was not waiting for new features and enhancements to be completed.

**Comment by lukasbestle** [comment]
@chrhuff Don't worry, it's not waiting. It just missed the cutoff for 3.6.x when we decided to work on 3.7.0 next. Major releases like 3.7.0 mean that we pause development on minor releases. I had planned to work on this issue for 3.7.0, but other projects that need to be in 3.7.0 because of breaking changes needed to get done first.

**Comment by lukasbestle** [comment]
I tried a lot of different variants to fix the issue with an automatic redirect. Unfortunately we cannot solve the issue this way because the redirect would be a security regression. You can read more details about the reasons for this at the end of this post.

There's a still a solution: Kirby 3.7.2 will [fix the back button regression](https://github.com/getkirby/kirby/pull/4517). So users can recover from the broken timeout state manually by clicking the back button, which will take them to the login form as expected.

---

Now for the detailed technical explanation why an automatic redirect won't work:

If we automatically logged the user out and threw them back to the login page when the timeout happens, attackers would get valuable information about the site:

- The timeout only affects "real" users as it's set by the auth challenge. If an attacker enters a random email address and `debug` mode is *not* enabled, Kirby will "fake" an auth challenge and still display the form for the login code. This avoids leaking the fact whether the user and therefore the email address exists. This fact can be used for malicious purposes, e.g. to find targets for further attacks. To solve the redirect in a way that makes the fake undetectable, we would have to fake the timeout as well. Unfortunately that's not possible. So by the fact that the Panel throws you back to the login page after a specified time for "real" users but not for "fake" users, attackers could again build themselves a list of existing users. Such a weakness is called an Observable Response Discrepancy. You can read more about it in this [OWASP guide](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#authentication-responses).
- Also attackers would be able to find out how long the timeout is. This isn't too serious on its own, but can be used to assess whether a social engineering attack is viable.

**Comment by distantnative** [comment]
@lukasbestle could you say a few words on why we can't fake the timeout? Would be curious to understand

**Comment by lukasbestle** [comment]
@distantnative With the current design of the auth challenge interface, the challenge can either generate a code specifically for this user (e.g. to be sent via email) or it can generate no code but check the code after it's entered (e.g. a TOTP code). Generated codes get a timeout but checked codes don't as they are checked anyway when they are entered.

Our current implementation detects the fact whether a challenge generates a code or only checks it [based on the return value of the challenge](https://github.com/getkirby/kirby/blob/cfac315bc685193d0fe1b10fe3bf45a96e48fd15/src/Cms/Auth.php#L127). But the challenge method can only be called for real users.

What we could do is to set a timeout even for challenges that don't generate a code. Then it would be consistent again and no Observable Response Discrepancy would occur. But then even a TOTP challenge would expire and the user would have to log back in. Thinking about it again, it's certainly a possibility, but not sure if that's a better UX (meaning I'm really not sure, could well be better). What do you think?

**Comment by lukasbestle** [comment]
I'll reconsider the automatic redirect for 3.7.3. The back button fix will still be in 3.7.2.

**Comment by lukasbestle** [comment]
✅
