### ISSUE TITLE
Block preview with numbers in preview name stopped working in 3.6.x

### ISSUE THREAD

**Issue by texnixe** [k-next/kirby#4104]
## Description
When a preview name contains a number, e.g `html5video`, an error is thrown.

Error when creating new block
> this.$refs[("block-" + t.id)][0] is undefined

Existing block
> t is undefined.

This seemed to have worked prior to Kirby 3.6. Changing the preview name to `htmlvideo` solves the issue.

Regression? Or was this changed on purpose?

**Expected behavior**  
The block should work like before.

## To reproduce
See thread: https://forum.getkirby.com/t/custom-block-type-broken-after-kirby-3-5-3-6-upgrade/24516

## Your setup
**Kirby 3.6.1.1**

**Comment by afbora** [comment]
@texnixe I did an independent test from the example on the forum, it seems to be working. Could it be another problem in the example in the forum? Have you tried a simple block preview that name contains number?

**Comment by texnixe** [comment]
@afbora I tested a simple custom block with numbers and that worked fine. I also tested the example from the forum again and it worked fine this time. No idea what was different the other day. So let's close this.

**Comment by iskrisis** [comment]
@texnixe for future support reference i think this can  happen because of case sensitivity. It happened to me twice already because i had some `fieldGroup.yml` block and when loading it i've used `fieldgroup: blocks/fieldgroup` by accident. At some point this has 100% worked and somewhere it has stopped (i know from updating project). 

It's double tricky because i think it is OS dependent. On Mac it works no matter the case but on Linux it is case sensitive. So very hard to track down when it stops on your server.

I think it should be case sensitive and issue then is why it works on Mac when it shouldn't.
