### ISSUE TITLE
[panel] Referrer policy blocks restricted APIs 

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#4121]
## Description
Kirby 3.4 introduced a Referrer Policy of `"same-origin"`, this blocks requests to APIs that restrict their access via referrer URLs. 
An example would be mapbox. 

**Expected behavior**  
Either make the referrer policy an option, or loosen it to something like `"origin"` or `"no-referrer-when-downgrade"`. 

## Your setup
**Kirby Version**:  3.4.0

**Additional context**  
Actually the correct way of solving this issue would be to specify a referrer policy on the image tags that make up, for example, the map tiles. But this requires a change in third party libraries like leaflet (and actually [something already did change](https://github.com/Leaflet/Leaflet/commit/f1f4e05ba1f530672423458e1f70ac44dee4fb77)), but the release cycle timing of Leaflet makes this seem like a rather impractical solution. 

As I'm not sure where to point this issue, I've posted the same on Sylvain's Locator Field plugin: https://github.com/sylvainjule/kirby-locator/issues/46

**Comment by sebastiangreger** [comment]
A related issue had been discussed in the past in PR #3677 (it all started [on the forum](https://forum.getkirby.com/t/vimeo-embed-in-panel/21226)) which also contains some arguments why I believe that `"no-referrer-when-downgrade"` is too loose for a CMS backend from a privacy/infosec perspective. As I argue in that discussion, `"strict-origin-when-cross-origin"` would be the only way to loosen this policy without risking the revelation of hidden URLs to third parties. It would only leak the domain, not a URL; personally, I still consider that no third party should know that links to them exist in the backend of some other domain, so this should be avoided if at all possible.

With the kirby-embed plugin, a similar issue got resolved by assigning a looser `referrerpolicy` to the iframe that embedded the video, see https://github.com/sylvainjule/kirby-embed/issues/5 – a similar adjustment was subsequently carried out to Kirby's core video embed element: https://github.com/getkirby/kirby/issues/3257

I am not familiar with the kirby-locator plugin, but since child elements inherit element-specific `referrerpolicy` settings from higher-level ancestors, could there be some element that such attribute could be assigned to, above the level where Leaflet gets involved? (I'll post a pointer over at that plugin-specific ticket…)

**Comment by distantnative** [comment]
@rasteiner @sebastiangreger based on your discussion in https://github.com/sylvainjule/kirby-locator/issues/46 I'd conclude to close this issue as this should be solved at the root by Leaflet and in the meantime via workarounds in plugins that load libraries that don't handle this properly yet (like Leaflet). Do you agree?
