### ISSUE TITLE
Option for ImageMagick memory limit

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#4248]
If ImageMagick uses more memory than the server allows, the process may get killed, which means that no thumb is created.
We can introduce a new `thumbs.memory` option to set the ImageMagick memory limit (defaults to `null` = no limit as before).

See https://github.com/getkirby/kirby/issues/3023#issuecomment-1021563151 and following posts.

**Comment by iskrisis** [comment]
AFAIK lowering memory limit wont help this. Not setting memory limit doesn't mean `null`/`unlimited` memory. It uses ImageMagick server policy config. So if the host is set up correctly there is no point to setting memory limit.

There are many limits in IM not just memory. Memory is whole process memory and by default IM will try to convert whole image in memory. This means that big images `6000x4000px` will need `6000x4000x32x3` bits = `288MB` of memory. If you set the memory limit to 256MB this image creation will fallback to cashing on disk (super slow also problematic for different reasons). And you actually need even more memory than 288MB to convert that image. 

But Imagemagick has also area, width, height, map limits. So for example if the area limit is set to `25MP` (5000x5000px) the 6000x4000 image straight up fails - no matter memory setting.

Setting all limits on cli is possible. But according to http://www.imagemagick.org/script/command-line-options.php#limit

```Note, you can restrict limits relative to any [security policies](http://www.imagemagick.org/script/security-policy.xml), but you cannot relax them.```
I don't think decreasing memory limit would be of any help.

**My takeaway**
If its your server you should set/tune these IM policy settings directly. If it's not your server than you are probably out of luck or you might need to communicate with admins maybe they can upgrade you.

**Comment by iskrisis** [comment]
Oh actually i think it used to be setting but according to http://www.imagemagick.org/script/command-line-options.php#limit 

`Note, you can restrict limits relative to any [security policies](http://www.imagemagick.org/script/security-policy.xml), but you cannot relax them.`

Which means that setting things on cli could only lower the memory limit. It might help on badly setup host i guess? But then the solution is to contact them.

**Comment by lukasbestle** [comment]
What do you think @silllli as the original author of this suggestion?

**Comment by silllli** [comment]
What @iskrisis writes is true, as far as I researched the topic. (In my current implementation I’m also using the `area` limit, `memory` is not sufficient or a misleading name.) I agree that the ImageMagick policy should be set correctly, but apparently it’s not on some shared hosting servers.

My suggestion would be exactly for this case:
> If it's not your server than you are probably out of luck

My experience was that I could get more images to be processed, although some large ones still fail, as I had already stated—probably due to hitting other hard limits like process runtime or I/O activity.

I would be happy if someone else could try this out, maybe my findings are wrong. You can test this easily by manually processing a large image using ImageMagick:

```php
<?php
exec('convert -debug "All" -limit area 10MB -define jpeg:size=1600x1600 "very-huge.jpg" -auto-orient -thumbnail 1600x1600! -quality 90 "small.jpg" 2>&1', $output, $retval); ?>

Status: <?= $retval ?><br>
Output:
<pre>
    <?= print_r($output) ?>
</pre>
```

**Comment by iskrisis** [comment]
There is so much unknowns in shared server conditions. Considering you can only lower the limits with CLI it's all getting into advanced wild goose chase territory. Users should almost always contact the admins.

I wanted to say allow people to add any flag (simple string to be inserted int command) for advanced usage because only memory limit is not satisfactory. But then i realized those users can just fork the and use modified 'im' driver. It's not hard and it's already so advanced territory that it should be fine.

We already agreed that right solution is to config server properly. Once you add this into docs somewhere people will start messing with memory/area thinking it will help which in most cases it won't. It might just create unnecessary support burden.

**Comment by lukasbestle** [comment]
> I wanted to say allow people to add any flag (simple string to be inserted int command) for advanced usage because only memory limit is not satisfactory. But then i realized those users can just fork the and use modified 'im' driver. It's not hard and it's already so advanced territory that it should be fine.

I think that's a good point. Since the IM thumb driver is a class, it can even be extended by a custom one, so only one method needs to be overridden (e.g. the `convert` method). It is not necessary to duplicate all the code.

This approach has the added benefit that we wouldn't need yet another core option.

To be honest I feel like we should close this issue. @silllli Does the custom thumb driver approach work for you?

**Comment by silllli** [comment]
Yes, I can totally live with it. I will have a look at simply extending the driver class myself—sounds good to me and keeps the core clean.

**Comment by nilshoerrmann** [comment]
@lukasbestle The whole image processing looks very complex from the outside: would it be possible to add a simple example to the docs how to extend an image driver class? Thanks!

**Comment by lukasbestle** [comment]
Good point. I have added a new reference page here:

https://getkirby.com/docs/reference/plugins/extensions/darkroom-drivers
