### ISSUE TITLE
Thumbs: Consider throwing an error instead of returning the source image when creating the thumb failed

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#4249]
See https://github.com/getkirby/kirby/issues/3023#issuecomment-1018032814 and https://github.com/getkirby/kirby/commit/0db632aa76484cb263cab8a9ed545a304d24048a#r33938782.

I think it's a good point. The original image is not only often much too large in file size, it will also not have modifications such as grayscale and cropping. Also the site owner may not want to leak the original image file to the public. An `HTTP 500` error will show clearly that something went wrong with generation of this thumb.

What do you think @getkirby/kirby-staff? What was the reason why we return the source image and is it still relevant today?

**Comment by iskrisis** [comment]
I think it's good idea. I've myself published websites that had thumb issues without me realizing it because i haven't noticed.

If it was setting i would be setting this on every website but setting it as default might bring upset people that relied on this without knowing :D.

**Comment by lukasbestle** [comment]
I wouldn't make this an option to be honest. Options always make Kirby more complex. If we can't think of any reason why someone might still want the current behavior, we might as well get rid of it completely.

**Comment by iskrisis** [comment]
Agree I wouldn't make this an option either. I am just thinking about backwards compatibility? This had to be deliberate decision for some reason. Maybe i just dont realize how it works. Kirby can't know if thumb creation failed right? It only knows the thumb is not there - but that also happens when the thumb haven't finished generation. Maybe this is better solution for first visits than flashing image errors. 🤷

**Comment by lukasbestle** [comment]
The thumb generation is blocking, so Kirby knows the thumb generation is either done or it failed.

Regarding the original motivation: That's the big question. Waiting for insights from the team, especially @bastianallgeier.

**Comment by andreasotto** [comment]
Good point!

Please link to #4145 i ran into trouble recently. Same topic imho.

I guess right now errors in thumbnail generation are quietly skipped?!
If there was error logging, we would have already gained a lot.

**Comment by iskrisis** [comment]
@lukasbestle i think the drivers throw the error correctly https://github.com/getkirby/kirby/blob/6b20fa11843f57cd9a1e611bc9e8e8a91b855156/src/Image/Darkroom/ImageMagick.php#L164 but if i understand correctly PHP error bubbling the erorr is swallowed somewhere here https://github.com/getkirby/kirby/blob/6b20fa11843f57cd9a1e611bc9e8e8a91b855156/src/Cms/Media.php#L131 and the source image is returned instead.

I know kirby doesn't do this anywhere but even if the source file fallback was kept i think it would be useful to log these. I've seen many people struggle with multi format generation just because they don't have recent `im` or it's build without the support. On shared hostings it's pain to debug since you often don't have shell access to try.

**Comment by lukasbestle** [comment]
@iskrisis Yes, see https://github.com/getkirby/kirby/commit/0db632aa76484cb263cab8a9ed545a304d24048a#r33938782.

Before we can discuss this further, we need insights on why we return the source image in the first place.

**Comment by lukasbestle** [comment]
@bastianallgeier Could you take a look at this open question? Maybe we can solve this together with #4632 (different issue, but same area in the code).

> What was the reason why we return the source image and is it still relevant today?

**Comment by jonaskuske** [comment]
Not stale

**Comment by bastianallgeier** [comment]
Sorry for the huge delay. I think the idea to not throw an error is an outdated concept. We had this in multiple places where we wanted to avoid unnecessary errors. But this often makes it a lot harder to actually debug problems. I would be completely open to throw errors instead.

**Comment by iskrisis** [comment]
When you create base64 string out of image thumbnail and your server is not creating thumbnails then Kirby creates the base64 from the original image. It's complete death for performance - much worse than serving the original image directly. 
It's even trickier to realize whats going on with base64 images. If you decide to keep serving original image then atleast this has to throw error and not create base64 version.

**Comment by lukasbestle** [comment]
I still think that it would overall be the most solid solution to throw an error and respond with HTTP 500.

**Comment by distantnative** [comment]
This will be in v4
