### ISSUE TITLE
Thumbs not generated when a content file with the thumb filename exists

### ISSUE THREAD

**Issue by andreasotto** [k-next/kirby#4276]
`3.6.4`

I found two situations where media files are not generated any more.

**Situation 1**

To reproduce start with an empty media folder.

Put two image files into a content folder (or upload through the panel).

```
file.jpg
file-720x.jpg
```

Use the first one `file.jpg` as the value in an image field in the blueprint.

In the template, try to output the image with something like: `$img->resize(720)`.

Result: No media file is generated. Kirby only generates the .jobs File. 
I don't understand why the second image in the content folder could have an impact on generated the media file for the first image file. They should not have any dependency.

**Situation 2**

*Moved to #4278*

**Comment by lukasbestle** [comment]
Thanks for your report. I have decided to split it up into a second issue at #4278 to avoid mixing the discussion and also because I can only reproduce this issue (situation 1):

What I found is that the job file is indeed generated correctly. But the `media` route to the image (as returned by `$img->resize(720)`) renders the error page. If I first generate the job file and then delete the extra content file, it all works as expected. So I believe the media route is not called for whatever reason when a content file with the same name as the thumb filename exists.

**Comment by andreasotto** [comment]
This still is buggy in 3.7.0

In the content folder we have the following situation:

```
-rw-r----- 1 www-data www-data 66616 Aug  2 14:08 andrea_foto_web.jpg
-rw-r----- 1 www-data www-data     0 Aug  2 14:08 andrea_foto_web.jpg.txt
```

In the media directory no image will be created. It is completely missing and in the panel and on the website frontend there are only broken images (404). Is this already scheduled to get fixed sooner or later? That do you suggest in the meanwhile?

**Comment by andreasotto** [comment]
We run into this situation with several customers on a regular basis. A customer uploads the same image a second time, with a similar name, e.g. Banner.jpg and Banner-720.jpg, and then a broken image appears on the website because no more media files are generated. 

Is there a workaround as long as this bug exists? 
It is hard to explain to the customer that he can break the system because he uploads a second image with a similar name.

**Comment by lukasbestle** [comment]
I think we need @afbora's debugging power 😊

**Comment by afbora** [comment]
I've tracked down the issue. I hope that helps you 🤞 

### Steps to the issue

1. Filenames for both are same in media folder. This is the main issue!
````html
<!-- name with resize value:  test + 720x -->
/media/pages/notes/test-4276/f7012712d7-1660342102/test-720x.jpg

<!-- original name as test-720x.jpg -->
/media/pages/notes/test-4276/6285b5144d-1660342304/test-720x.jpg
````

2. Runs `Media::link` for page files in routes 
https://github.com/getkirby/kirby/blob/3.7.3/config/routes.php#L68-L74

3. `Media::link` method checks the file (`test-720x.jpg`) existence for the page
https://github.com/getkirby/kirby/blob/3.7.3/src/Cms/Media.php#L43

4. Found the file but if hash not same (because it found the file with the original name, so wrong file found), returns false instead of regenerate the thumb
https://github.com/getkirby/kirby/blob/3.7.3/src/Cms/Media.php#L52

### Possible solution (POC)

Seems works well when you regenerate instead returning false. The code example below is not exactly a solution proposal. Just proof of concept..

````php
public static function link(Model $model = null, string $hash, string $filename)
{
    ...
    if ($file = $model->file($filename)) {
        ...
        
        if ($file->mediaHash() !== $hash) {
            if (Str::startsWith($hash, $file->mediaToken() . '-') === true) {
                ...
            } else {
                // try to regenerate
                return static::thumb($model, $hash, $filename);
            }
        }

        ...
    }

    // try to generate a thumb for the file
    return static::thumb($model, $hash, $filename);
}
````

https://github.com/getkirby/kirby/blob/3.7.3/src/Cms/Media.php#L61

**Comment by distantnative** [comment]
An alternative could also be to always append a suffix to all media files, even if no modifications are made. That way no unmodified name can be same as a similar modified name.

**Comment by lukasbestle** [comment]
Maybe we could put all thumbs in a subdirectory like so:

```
// copies of the unmodified files
/media/pages/notes/test-4276/6285b5144d-1660342304/test.jpg
/media/pages/notes/test-4276/6285b5144d-1660342304/test-720x.jpg

// thumbs
/media/pages/notes/test-4276/6285b5144d-1660342304/thumbs/test-720x.jpg
/media/pages/notes/test-4276/6285b5144d-1660342304/thumbs/test-720x-720x.jpg
```

Then they can never clash with original files.

@distantnative Ah, missed your comment. Seems like we had the same idea. What kind of suffix do you have in mind?

**Comment by distantnative** [comment]
Could be something like `-raw` or so. Sub folder could work too but might be more work to handle different directories compared to just a change to naming.

**Comment by lukasbestle** [comment]
Ah, I see. But then the filename of the original file would be modified e.g. when the file is downloaded.
If we do it the other way around however (suffix for thumbs), then it's again no longer guaranteed that there are no collisions. Difficult...

**Comment by distantnative** [comment]
Is that a problem? We also modify the names for thumbs etc. - don't quite see that this would be an issue.

**Comment by lukasbestle** [comment]
IMO it would be a breaking change. If you want to provide original files (e.g. PDFs, ZIPs but also images) as downloads, you would expect Kirby not to mess with the filename. E.g. we do that in the presskit on getkirby.com.

**Comment by distantnative** [comment]
Actually I think the subdirectory solution would work if all as we'd be moving the problem just to a different spot. Now we would rely on having no subpage called thumbs.

**Comment by lukasbestle** [comment]
No, the subpage thumbs would have the following media URIs:

```
/media/pages/notes/test-4276/thumbs/6285b5144d-1660342304/test.jpg
/media/pages/notes/test-4276/thumbs/6285b5144d-1660342304/thumbs/test-720x.jpg
```
