### ISSUE TITLE
Corrupted media on first serve because of stray whitespace

### ISSUE THREAD

**Issue by iskrisis** [k-next/kirby#4391]
## Description
Before media files are moved to the media folder - when they are server through Kirby/PHP. If you accidentally output something you will corrupt the file thats about to be served. 

This is as easy as starting `<?php` on second line in a plugin instead of first line.

## Expected behavior 
It would be great if there was some safety. One would either get error or the output was thrown away. It is really hard to debug. I spend multiple hours trying to debug something that turned out to be empty line in beginning of file in some plugin. It's hard to notice because all other stuff - json/html is fine plus after the first page load its also fine for most users.

## To reproduce
Output whitespace anywhere - in entry `index.php`, `config/config.php`, `plugins/index.php` like
```php
//have

//empty line here
<?php
 mycode();
```

Tested on Kirby 3.6.6. but i assume it happens on all versions.

**Comment by distantnative** [comment]
Honestly, not sure how we could detect and react to that - don't think the script itself can be aware of its surroundings in such a way

**Comment by iskrisis** [comment]
I also don't know but in my naive understanding:
1. I thought maybe before kirby runs userspace code it starts output buffer that gets emptied in the end - so maybe it can be gathered before doing this other work.
2. Googling mentioned checking https://www.php.net/manual/en/function.headers-sent.php  as way to check if outputing to users has already started.

I understand this might be unsolvable. It should be on the authors and its even bad idea to swallow such mistakes (no matter how easy is to make it). But its very invisible we simply don't get any error nothing. I bet i am not first one stumbling on this its just very hard to spot. One little mistake in public plugin could suddenly break websites without people even knowing it.

**Comment by lukasbestle** [comment]
We discussed this in the team and are all on the same page that Kirby cannot prevent such issues. You are right that it could be done with output buffering, but that would have enormous impacts on reliability and performance and would also make it harder to debug other issues.

But what we could do is to make accidental output immediately visible by throwing an exception.

## Implementation idea

All userspace PHP code is loaded by Kirby's `F::load()` and `F::loadOnce()` methods. These could be extended to check for accidental output:

- Both methods would get a new argument `bool $allowOutput = true`. The default is `true` to avoid a breaking change. Also this check isn't always needed. E.g. when a snippet or template is loaded, output is intended.
- If the option is set to `false`, the methods would call a new method like `Http\Response::guardAgainstOutput($closure)` with a closure that handles the file inclusion. The new method would check for `headers_sent()` before and after calling the `$closure`. If the headers weren't sent before the closure was called but are sent afterwards, then we know that the included file must have caused output. In this case we would throw an exception like "Disallowed output from file $file:$line, possible accidental whitespace?"
- We could also add this check in `F::loadClasses()` (here without the option as class files should never produce output). We don't use this method anywhere in the core, but for consistency it might make sense to add the behavior to it as well.
- Also we should consider if `Toolkit\Component::setup()`, `Cms\Loader::resolve()` and `Cms\Blueprint::preset()` can be changed to use `F::load()` instead of `include`/`require` directly.

**Comment by iskrisis** [comment]
Perfect. I also think the error is much better solution. If there was even vague error you immediately know there is issue and you can figure it out from changes between commits.

Hope this won't be too much work or possibly introduce different problems. But if isn't too bad it's good quality of life improvement.

**Comment by distantnative** [comment]
But if the default is true, @iskrisis would still not get a warning for his cases with core loading PHP files with whitespace.

**Comment by lukasbestle** [comment]
Of course we would pass the `false` value everywhere in the core where it makes sense.

**Comment by distantnative** [comment]
✅
