### ISSUE TITLE
[3.7.0-rc.1] blueprint: type: pagetable is shows no pages inside

### ISSUE THREAD

**Issue by clausarnold** [k-next/kirby#4417]
## Description
When in blueprint the type: pagetable is chosen to show pages in the folder nothings shows in panel....
--> with plugin sylvainjule/pagetable

**Comment by distantnative** [comment]
Fixed with RC.2

**Comment by afbora** [comment]
@clausarnold This issue is not Kirby related. The plugin is not yet 3.7 compatible. I've created an issue https://github.com/sylvainjule/kirby-pagetable/issues/81

**Comment by trych** [comment]
I would argue that this issue *is* indeed related to Kirby.

I have some panel setups that heavily depend on this plugin and on having a table that I can sort ~~and filter~~. The new table layout for pages sections is not an adequate replacement as it lacks the column sorting ~~and the filtering / search field~~.

As it stands Kirby 3.7 totally breaks my workflow for these projects and I am unable to update (and even unable to set up new projects with similar requirements in 3.7). Usually, I'd expect a dot release not to break backwards compatibility, especially not for a paid product.

Could I kindly ask Kirby developers to look into this and maybe provide a fix for this plugin? Maybe you have a good understanding of why exactly it is now incompatible and how it can be fixed. Thank you!

**Comment by lukasbestle** [comment]
> Usually, I'd expect a dot release not to break backwards compatibility, especially not for a paid product.

This is a misunderstanding. We use semantic versioning with an additional "generation" added in the beginning of the version number. So 3.7.0 is actually 3.7.0.0, which means generation 3, major 7, minor 0 and patch 0. We omit the patch for brevity if it's zero. Every major release (3.5, 3.6, 3.7 etc.) has had breaking changes. We are very careful with these breaking changes, but sometimes we need them to bring Kirby forward. Otherwise we would accumulate a lot of cruft.
