### ISSUE TITLE
Blocks: pasting formatting lists removes spacing

### ISSUE THREAD

**Issue by bogdancondorachi** [k-next/kirby#4702]
## Description
When you try to paste/import some text from your clipboard that has lists that are formatted, the text of the list is rendered without the spaces around the formatted text.

**Expected behavior**  
The text of the list should be kept exactly as copied

**Screenshots**  

https://user-images.githubusercontent.com/39380741/192341077-1ecec363-23d4-431b-8b49-0cf7001d9f50.mp4

## To reproduce

1. Go on panel to a page that has blocks
2. Add some test list with list block
3. Add formatting to some words like bold, link
4. Save and open page
5. Copy the frontend rendered list
6. ctrl+v or paste on the blocks again
7. You should see that the same text appear without spaces around the words you've formatted

## Your setup
**Kirby Version**  
3.7.5

**Console output**  
nothing on console

**Your system (please complete the following information)**
 - Device: Laptop
 - OS: Windows 11
 - Browser: Edge
 - Version: 105.0.1343.50

**Additional context**  
It seems that if I add a list block then paste the text inside it, it will render as it should. Only when trying the ctrl+v function seems to not work.

**Comment by afbora** [comment]
## Issue summary

@bastianallgeier I've tracked down the issue and this issue occurs by following `trim` function
https://github.com/getkirby/kirby/blob/3.8.0-rc.2/src/Parsley/Inline.php#L31

Works great when I removed the `trim` but I'm not sure about the solution. You know better since you're author of Parsley class.

**Comment by distantnative** [comment]
@afbora could you set up a PR with that fix? And then we can do more manual testing if we run into other side effects.

**Comment by afbora** [comment]
I understand exactly what the problem is, but I have no idea of a solution. 
@bastianallgeier can you help me with this? Here is the process of issue:

1. This method is executed for block list items on paste:
https://github.com/getkirby/kirby/blob/3.8.3/src/Parsley/Schema/Blocks.php#L189
2. For each dom element in each line, the following line is executed:
https://github.com/getkirby/kirby/blob/3.8.3/src/Parsley/Schema/Blocks.php#L200
3. The Inline class then deletes the space at the beginning and end of each dom element:
https://github.com/getkirby/kirby/blob/3.8.3/src/Parsley/Inline.php#L31
4. Then each dom element is joined adjacent to each other:
https://github.com/getkirby/kirby/blob/3.8.3/src/Parsley/Schema/Blocks.php#L202-L206
5. Thus the spaces between dom elements are lost.

_When we remove trim function in Inline class, the ones with a single element are broken._
