### ISSUE TITLE
[3.8.0-rc.3] UUID cache creates excess write operations while browsing the panel

### ISSUE THREAD

**Issue by sebastiangreger** [k-next/kirby#4757]
## Description
I am not sure is this unavoidable or even intentional, but I noticed that browsing around the panel triggers a huge amount of write operations in the file cache. It also appears that most of these write requests are duplicated, i.e. the cache writing operation always occurs twice for each UUID.

**Expected behavior**  
I would expect that already existing files in the UUID cache don't have to be overwritten repeatedly while content is not changing.

## To reproduce
1. Use a fresh Starterkit and update to 3.8.0-rc.3
2. Create `site/templates/sandbox.php`
3. Add `<?php Kirby\Uuid\Uuids::populate();` into that sandbox template
4. Call URL `/sandbox` once to ensure all content has a UUID
5. In `kirby/src/Cache/FileCache.php` add the line `F::write(kirby()->root('logs') . '/cachedebug.txt', date('H:i:s') . ' ' . $key . "\r\n", true);` in line 131, just before the `F::write()` call of the `set()` method
6. Open the panel and navigate around a bit (e.g. to the Notes view, into a single Note and back)
7. Access the log file `logs/cachedebug.txt`, see the amount of write requests created and how they always come in pairs

## Your setup
3.8.0-rc.3

**Comment by distantnative** [comment]
Does this get better when you replace https://github.com/getkirby/kirby/blob/develop/src/Uuid/Uuid.php#L330 with

```php
if ($this->isCached() === false) {
    $this->populate();
}
```
?

**Comment by sebastiangreger** [comment]
Based on a quick test (I deleted the UUID cache folder to start afresh), absolutely. Once populated the excess writes seem to be gone :+1:

I still get occasional double-writes when a not-yet-cached page is listed in the panel, though – some kind of race condition?

**Comment by distantnative** [comment]
Race condition could very well be there - multiple sections triggering the same UUID creation. But that might be tolerable.

**Comment by distantnative** [comment]
Alternatively one could check on each populating action whether its already cached: https://github.com/getkirby/kirby/blob/develop/src/Uuid/Uuid.php#L305

That would be even safer, @lukasbestle do you think there is a problem with that?

**Comment by lukasbestle** [comment]
> Alternatively one could check on each populating action whether its already cached

@distantnative Sounds good as a first step. Reading from any cache is much less expensive in terms of storage wear and performance than writing to the cache. So the more we can avoid writes by checking first, the better.

Maybe we could improve this later by checking if the UUID object was created by loading the reference from the cache. In this case we already know that the cache is populated correctly, so we can avoid the extra check. So basically, in `populate()` we would first check how the instance was loaded. If from cache, we return early. Otherwise we call `isCached()`. If that also returns `false`, we finally store to cache.

**Comment by distantnative** [comment]
✅
