### ISSUE TITLE
Draft pages include uuid when content.uuid option is false

### ISSUE THREAD

**Issue by splorp** [k-next/kirby#4787]
## Description

I currently have `content.uuid` set to `false` in the Kirby config file. This works as promised per PR #4755 and does not add `Uuid:` fields to my existing content. (Thank you!)

However, if I create a new draft page in the panel, a `Uuid:` field is added to the content, even though the config is set to false.

**Expected behavior**  

When `'content.uuid' => false` do not add the `Uuid:` field to new draft pages.

## To reproduce

1. Go to `website/panel/site`
2. Click on ‘Add’
3. Fill in the required fields and click ‘Create draft”
4. Open the content file: `content/_drafts/title-of-draft-page/page.txt`
5. Observe the unwanted `Uuid:` field

## Your setup
**Kirby Version**  
3.8.1-rc.1

**Console output**  
n/a

**System**
- Device: MacBook Pro
- OS: macOS 10.13.6 High Sierra
- Browser: Vivaldi
- Version: 5.5.2805.35 (Chrome/106.0.5249.113)

**Comment by lukasbestle** [comment]
I think `Uuid::generate()` also needs to check for the option and return `null` if UUIDs are disabled. @distantnative?

**Comment by distantnative** [comment]
@lukasbestle No I think that would be the wrong place. The generator might be used for other functionality unrelated to the config option. I think we rather need to look at where the uuid is actually added in the page actions.

**Comment by lukasbestle** [comment]
I'm curious: What could the "other functionality" be specifically?

I think it would be much more DRY to handle this here. Otherwise we would need to duplicate the behavior into all `PageActions`, `FileActions` and later the blocks/structure fields as well. We could do that, but only if there really is a use case for UUID generation with disabled option.

**Comment by distantnative** [comment]
E.g. the plan is to use `Uuid::generate()` also for blocks to have one consistent format instead of the current `Str::uuid()`. But blocks will always need their id, no matter if `content.uuid` is disabled as it mainly is there to prevent the extra uuid fields for pages and files in the content files. Blocks (and in the future also structure fields I believe) will still need an id, even if the UUID feature is disabled. Disabling the generator would totally break such use cases that we even have in the core.

**Comment by bastianallgeier** [comment]
✅

**Comment by splorp** [comment]
Thanks, all!
