### ISSUE TITLE
Vue devtools not working in Panel

### ISSUE THREAD

**Issue by ovenum** [k-next/kirby#4796]
## Description

While developing panel plugins or learning about the core panel Vue components and structure it’s really nice to use [Vue.js devtools](https://vuejs.org/guide/scaling-up/tooling.html#browser-devtools) for debugging or just to get a good overview of how the panel works. I would consider them an integral part for Vue development. 

For reasons beyond me, i can’t get them to show up in the panel. Vue.js is detected by the DevTools plugin but it won’t show in the Browsers DevTools Panel (Chrome and Firefox). 
The Vue devtools [trouble shooting guide](https://devtools.vuejs.org/guide/faq.html#the-vue-devtools-don-t-show-up) suggest to use a non-minified build, no sure if this a requirement or suggestion.

Vue devtools will check `window._VUE_DEVTOOLS_GLOBAL_HOOK__.Vue` for the Vue instance, which is null for production builds or when `Vue.config.devtools` is false during build. 

Does the panel expose the Vue instance somewhere so it can be bound manually from a plugin? 
Or should Kirby supply two panel builds and switch between them when `debug = true` in Kirbys config file? 

**Update**
While searching the `panel/dist` folder for `devtools` i noticed that index.js sets devtools to true and vendors.js sets it to false. Setting devtools to true inside `media/panel/vendor.js` will enable Vue devtools in the Browsers Dev panel.

**Expected behavior**  

To use Vue devtools for panel debugging without re-building the panel source with the right flags.

## Your setup
**Kirby Version**  
3.8.0

**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: macOS 12
 - Browser: Chrome and Firefox
 - Version: @latest

**Additional context**

**Comment by lukasbestle** [comment]
This might be related to #4735, which is about exposing the global `window.Vue` object.

**Comment by ovenum** [comment]
Thanks for pointing to that insightful read! 
Following @jonaskuske [solution](https://github.com/getkirby/kirby/issues/4735#issuecomment-1264520959) on how to access the panels Vue instance, i could bind it to `window.__VUE_DEVTOOLS_GLOBAL_HOOK__.Vue` and the devtools are working again  🎉

```js
panel.plugin("namespace/plugin", {
  use: {
    plugin(Vue) {
      // Check for VueDevtools Browser plugin
      if (window.__VUE_DEVTOOLS_GLOBAL_HOOK__) {
        window.__VUE_DEVTOOLS_GLOBAL_HOOK__.Vue = Vue;
      }      
    },
  },
};
```

Without doing this the weird thing is that `Vue.config.devtools` is true already but `window.__VUE_DEVTOOLS_GLOBAL_HOOK__.Vue` is still null. Not sure what’s going on there. 

Also this will not work with Vue3 as all devtools related code will be [tree shaken](https://github.com/vuejs/devtools/issues/1308#issuecomment-867987584) from the production build.

> It is actually saving size and performance for Vue 3, as be strip out all the devtools related code by default in the production builds (with [build flags](https://github.com/vuejs/vue-next/tree/master/packages/vue#bundler-build-feature-flags)).

**UPDATE**
In the above code snippet it’s required to check for the `window.__VUE_DEVTOOLS_GLOBAL_HOOK__` before assigning the panel Vue instance. If the VueDevtools browser plugin is not installed with the browser using the panel, the panel will break.

**Comment by jonaskuske** [comment]
> Also this will not work with Vue3 as all devtools related code will be https://github.com/vuejs/devtools/issues/1308#issuecomment-867987584 from the production build.

Yeah, with Vue 3, Kirby will have to add a config option that allows loading the development version of Vue. (and automatically load it if a plugin dev server is running)
Otherwise dev tools won't work, and also live reload for plugin development will break, as in Vue 3 the HMR runtime is part of Vue instead of external, and thus not loaded if Kirby loads the minified build of Vue. But that's not a problem for now :)

**Comment by distantnative** [comment]
This should work once we switch to Vue 3 and expose the bundles in a better way. We are working towards this in the mid-term. I'll close the issue to have a better overview for us in the repo and this will be solved eventually automatically once we switch.

**Comment by Daandelange** [comment]
Hello,
Sorry to revive this issue but I lost quite some time trying to get Vue to be detected from the Vue devtools in Firefox lately.
(_it would appear once every 20 reloads..._)

My setup might a bit outdated but the point is that it works with the above code snippet so it is clearly related.
If I understand it correctly, the issue hasn't been fixed in k5, but "postponed" to K6=Vue3.

Until Kirby6 is out, would it be an idea to add this in the documentation ? Or temporarily inject it by default when `options.panel.debug` is true ? (ping: @distantnative) 
Another handy info to document could be that `vue-devtools 3.1` depreciated `Vue2`, thus K5 advanced-plugin-dev requiring `vue-devtools 3.0.x`.

**Comment by distantnative** [comment]
@Daandelange It's great if the hack above works to solve your issue but I don't think it's something we should add to the core in v5, just too unstable.

In v6 this should be already possible when Kirby detects a `.vite-running` file in the `site/plugins` folder. We're working together with @johannschopplich do that kirbyup writes that file temporarily while working on any plugin with `npm run dev`.
