### ISSUE TITLE
Files field mime type constraint not respected when using `Select`

### ISSUE THREAD

**Issue by doup** [k-next/kirby#4823]
## Description

- Imagine a content type, with two `files` fields, one allows to upload PDF files, the other one EPUB files.
- When uploading the mime type constraint is applied correctly in the file picker (see: https://github.com/getkirby/kirby/issues/1877)
- But, if the user uses the `Select` option, all the uploaded files regarding of their mime type are shown and any of the can be selected. This makes possible to load a PDF on a field that only allows EPUB files.

**Expected behavior**  

When using `Select` it should honour the mime type constraint and only show the files that match with the mime type.

**Additional context**  

This was already reported in: https://github.com/getkirby/ideas/issues/495
Looks like a good assumption that if you're limiting the upload mime, then the select mime should also be limited.

Sonja tells me that it's expected behaviour and that `query` should be used: https://forum.getkirby.com/t/do-i-need-to-do-anything-special-to-upload-epub-files/26834/6 I'm not sure if this is good UX.

**Comment by afbora** [comment]
@doup as I'm author of https://github.com/getkirby/ideas/issues/495 idea; I think, would be good if move this idea to https://feedback.getkirby.com

**Comment by lukasbestle** [comment]
For the most common cases, using the `uploads` option also for selecting makes sense.

However it would limit the flexibility for advanced use cases. E.g. you may want to allow selecting files from a central media repository (a top-level page) but also to upload new files just for this one page.

Also it would reduce performance because all results of the query would also need to be filtered.

And finally I think it's inconsistent regarding the syntax. The option is called `uploads`, so it would IMO be weird if it also applies to selected files. If we want to combine both into one, the option would need to be renamed.

I'm closing the issue for now as I agree with Ahmet that it rather belongs on the feedback platform. @doup Feel free to add the idea there if you are still interested.
