### ISSUE TITLE
[3.8.3-rc.1] Regenerating UUIDs for files when duplicating nested page wih Panel UI

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#4875]
## Description

#4864 issue not fixed totally. When duplicating a page with subpages, the `files` argument is sent as `false`. Because there is no `Copy files` toggle in the dialog.

https://github.com/getkirby/kirby/blob/develop/config/areas/site/dialogs.php#L499-L503

Since we call the ->duplicate() method directly in our unit tests, it passes the tests, but when we do it from the panel, the parameters are not sent correctly.

### Dialog on single page
![captures_chrome-capture-2022-10-29 (2)](https://user-images.githubusercontent.com/3393422/204552655-81547f60-523f-4d4f-b7ce-0cd0bf4044ec.png)

### Dialog on nested page
![captures_chrome-capture-2022-10-29](https://user-images.githubusercontent.com/3393422/204552816-a4e7ac89-26a1-4414-bc84-8cd253410f25.png)

## Your setup
**Kirby Version**  
3.8.3-rc.1

### Possible solution

1. Available both toggle for nested page dialog
2. If the `Copy pages` (children) toggle is selected, `files` argument should always be `true`

**Comment by afbora** [comment]
@getkirby/kirby-staff What do you think about we should move with which option?

- Adding `Copy files` toggle for the dialog when duplicating nested pages
- Fallback `files` argument as `true` when duplicating nested pages *

_* This is already the default behavior but not as a parameter. Also the parent page's files can be ignored but not its children._
https://github.com/getkirby/kirby/blob/3.8.3-rc.1/src/Cms/PageActions.php#L491-L500

**Comment by lukasbestle** [comment]
TBH I don't fully grasp the issue yet:

- Do the current UI toggles actually break the UUID regeneration, meaning a file or subpage is duplicated but without replacing its UUID?
- As far as I understand it, if the user enables "Copy pages", the files of the subpages are copied too and there is no way to only copy the subpages without files, right?

**Edit:** Ah, I might have answered my own question. If I understood the second point correctly (copying subpages always copies the files), the issue is that the files of subpages are duplicated but not adapted (because `$files` is `false`). Correct?

**Comment by afbora** [comment]
> Ah, I might have answered my own question. If I understood the second point correctly (copying subpages always copies the files), the issue is that the files of subpages are duplicated but not adapted (because `$files` is `false`). Correct?

Exactly!

**Comment by afbora** [comment]
Simple solution for `files` argument could be something like following.

````php

$newPage = Find::page($id)->duplicate($request->get('slug'), [
    'children' => (bool)$request->get('children'),
    'files'    => (bool)$request->get('files') || (bool)$request->get('children'), // fallback solution
    'title'    => (string)$request->get('title'),
]);
````
https://github.com/getkirby/kirby/blob/develop/config/areas/site/dialogs.php#L499-L503

---

Or in `PageActions::copy()` method

````php
$children = $options['children'] ?? false;
$files    = $children || ($options['files'] ?? false);
````
https://github.com/getkirby/kirby/blob/develop/src/Cms/PageActions.php#L464-L465

What do you think?

**Comment by lukasbestle** [comment]
I wonder what the reason is that the UI only shows one of the two toggles but never both. With the current UI I'd expect that the files of subpages are always ignored. It's inconsistent that the files of the current page are ignored but the files of subpages are copied.

So I guess the question is what the user expects. I'm personally leaning towards displaying both toggles for subpages *and* files. If only subpages are enabled but not files, only the pages without files would get copied.

However that wouldn't be doable for 3.8.3.

**Comment by afbora** [comment]
If we want to have two toggles, as you said, it is a bit difficult and risky to move it to 3.8.3 (we can add it to nolt and follow it from there). Therefore, I think that the fastest and most stable solution is to apply the solution in this comment https://github.com/getkirby/kirby/issues/4875#issuecomment-1333408906

**Comment by distantnative** [comment]
I also can already tell that when we add two toggles we'll receive the immediate request/issue how to duplicate with files of the duplicated page itself and its subpages, but those subpages without files 🙈

**Comment by lukasbestle** [comment]
> If we want to have two toggles, as you said, it is a bit difficult and risky to move it to 3.8.3 (we can add it to nolt and follow it from there). Therefore, I think that the fastest and most stable solution is to apply the solution in this comment [#4875 (comment)](https://github.com/getkirby/kirby/issues/4875#issuecomment-1333408906)

I just looked at the [dialog code](https://github.com/getkirby/kirby/blob/develop/config/areas/site/dialogs.php#L464-L480) again and realized that there *can* be both the subpages and files toggle at the same time. This is the case when the current page has both subpages and its own files.

So to summarize the current status:

- If the page doesn't have subpages, everything works as expected on `develop`.
- If the page has subpages and the subpages have files, the files are not updated with new UUIDs (which is a bug) if and only if the "files" toggle is not enabled.
- If the page has both files and subpages, both toggles appear and if both are enabled, everything works as expected.

---

Regarding solutions:

I think it would be a breaking change to always copy files if the subpages toggle is enabled. Because it would override the user selection if the page has its own files, but the user does *not* want them copied.

A possible solution could be to pass `$files` as `true` only when adapting subpages. The duplicated root page would be unaffected and behave as before:

```diff
- $this->adaptCopy($child, $files);
+ $this->adaptCopy($child, true);
```

(this would need to be done for both branches, multilang and single-lang)

**Comment by bastianallgeier** [comment]
✅
