### ISSUE TITLE
If null is passed to snippet helper, `$file` in snippet component is undefined

### ISSUE THREAD

**Issue by texnixe** [k-next/kirby#5004]
## Description
When calling `snippet()` with a dynamic method that returns a `null` value

```
snippet($page->field()->value());
```
`$file` in the snippet component is undefined. This error could be prevented by initializing `$file`.

## Your setup
**Kirby Version 3.8.4**

**Comment by lukasbestle** [comment]
With the changes in 3.9, the behavior changed so that `snippet(null)` will produce a fatal error because the argument type in the snippet component is defined as `string|array $name`.

There are three possible solutions:

1. Either we change the type hints and method code to fully support `null`. If `null` is passed, an empty snippet is rendered.
2. Or we keep the current type hints, but convert a `null` value to an empty string in `$app->snippet()`. The result would be the same.
3. Or we enforce the type hints and only allow `string|array` for `$app->snippet()` and the `snippet()` helper.

Currently leaning towards option 1 as it's the most user-friendly.

**Comment by bastianallgeier** [comment]
✅
