### ISSUE TITLE
Try...Catch in Response.__toString hides errors

### ISSUE THREAD

**Issue by tzugen** [k-next/kirby#5027]
## Description
I am working on a extension for a templating engine.
At some point I placed a `var_dump` statement in my code.
Later I realized that Kirby produced no output at all anymore.

I took me some time to realize that when I called var_dump()
1. $this->send() failed because it tried to change headers after I already sent data
2. But more importantly the whole error just vanished. I would strongly argue that if $this->send() fails, it should not silently swallow the error, but throw it up.

https://github.com/getkirby/kirby/blob/066b0506a81fdd331edc54add601d907a61ebbb4/src/Http/Response.php#L86-L98

**Comment by lukasbestle** [comment]
I agree that catching any error and throwing it away is really not a good solution. However I'm currently struggling to find which problem this code tried to solve.

The `try catch` code has been in Kirby since the very first commit of this repo (so at least since Kirby 3.0.0). @bastianallgeier Do you remember why we use `try catch` in this place?

**Comment by bastianallgeier** [comment]
I'm sorry, but I really cannot remember. We used to "hide" a lot of errors in the v2 and early v3 days, which never was a good decision. I'd say that we should remove the try/catch here. 

I just wonder if we should do this in a minor or a major release.

**Comment by distantnative** [comment]
Probably major release, just because it bears a lot of risk for regressions.

**Comment by distantnative** [comment]
This will be solved in v4
