### ISSUE TITLE
locale matching does not work

### ISSUE THREAD

**Issue by therephil** [k-next/kirby#5135]
## Description
Locale matching with language detection does not work with multiple locales for the same language.
`en-US` always just matches `en`when present. 

In https://github.com/getkirby/kirby/blob/main/src/Cms/App.php#L588 the language never matches for the locale. It's always the code that matches in the end. 
The reason lies in https://github.com/getkirby/kirby/blob/main/src/Toolkit/Collection.php#L413 because that compares an array (the locale configuration of a language) with a string (the locale string from the users browser language).

and because `en_US` is really not `array (6 => 'en_US')`
that part will never match anything.

**Expected behavior**  
I would expect the that the locale array is resolved to just `LC_ALL` so a match can happen and the user is redirected to the correct page

## To reproduce
In a fresh plainkit I create three languages:
de.php
```php
<?php
return [
    'code' => 'de',
    'default' => true,
    'direction' => 'ltr',
    'locale' => 'de_DE',
    'name' => 'Deutsch',
    'url' => '/de/'
];
```

en.php
```php
<?php
return [
    'code' => 'en',
    'default' => false,
    'direction' => 'ltr',
    'locale' => 'en_GB',
    'name' => 'English (EU)',
    'url' => '/en/'
];
```

us.php
```php
<?php
return [
    'code' => 'us',
    'default' => false,
    'direction' => 'ltr',
    'locale' => 'en_US',
    'name' => 'English (US)',
    'url' => '/us/'
];
```

and in the config set languages active and language detection to active
```php
return [
    'languages' => true,
    'languages.detect' => true,
];
```
visit homepage with browser language set to `en-US`

## Your setup
**Kirby Version**  
Current Plainkit 3.9.3

**Your system (please complete the following information)**
 - Device: MBP 16" 2021
 - OS: mac os 13.2.1
 - Browser: firefox, chrome. Set language to en-US
 - Version: doesn't matter

**Additional context**  
kirby running in a ddev managed docker container

**Comment by afbora** [comment]
### Summary

[Here](https://github.com/getkirby/kirby/blob/3.9.3/src/Cms/App.php#L589) we are scanning through the `locale` prop, but the `locale` value in the languages collection always returns array even if `string` is set in config.php. That's why it can't find the right locale.

````
array(7) {
    ["code"]=>
    string(2) "en"
    ["default"]=>
    bool(false)
    ["direction"]=>
    string(3) "ltr"
    ["locale"]=>
    array(1) {
      [0]=>
      string(5) "en_GB"
    }
    ["name"]=>
    string(2) "EN"
    ["rules"]=>
    array(0) {
    }
    ["url"]=>
    string(47) "http://localhost/test/kirby/starterkit-3.9.3/en"
}
````

To give you an idea, it works when we search for it as an array in the collection. Of course, I am not sure if it will work in different locale settings.

````diff
-if ($language = $languages->findBy('locale', $lang->locale(LC_ALL))) {
+if ($language = $languages->findBy('locale', [$lang->locale(LC_ALL)])) {
     return $language;
   }
````

**Comment by lukasbestle** [comment]
Thanks for investigating, @afbora!

I think that will only work if the configured language only defines a single locale. As soon as other `LC_` constants are defined, the array will contain more than one value and will not match.

Instead we need to grab the `LC_ALL` locale string from each language object and compare it to the visitor locale.

For a clean implementation, we need callback support for `$collection->findBy()`. Then we could do something like this:

```php
if ($language = $languages->find(fn ($language) => $language->locale(LC_ALL), $lang->locale())) {
	return $language;
}
```

(BTW, that `LC_ALL` that we currently have in the call for `$lang->locale()` seems to be useless, so I removed it. Because `$lang` is an `Obj` object that does not define arguments for the `locale()` method at all.)
