### ISSUE TITLE
Square brackets in filenames throwing an error in panel

### ISSUE THREAD

**Issue by MikeHarrison** [k-next/kirby#5168]
## Description
I have a front end form where visitors can upload files. Files uploaded with square brackets - [ ] - in the filename are causing an error in the panel when they are clicked on in a files section.

**Expected behavior**  
Clicking on a file opens the file view

**Observed behavior** 
Clicking on a file in the file section shows the error message `The view could not be found`

## To reproduce

1. Manually add a file to a page directory with a set of square brackets in the filename
2. Create a files section in the panel for this page
3. Click on the file

## Your setup
**Kirby Version**  
3.9.1

**My system**
 - Device: Mac mini 2018
 - OS: macOS Ventura 13.3.1
 - Browser: Firefox
 - Version: 112.0.2

**Comment by bastianallgeier** [comment]
I'm afraid we can't properly support those. Are the brackets important for the file names? Could the filename maybe be sanitized on upload?

**Comment by MikeHarrison** [comment]
Hi,
No they aren't important, I have added a find/replace to deal with them for future uploads. Thought it was worth letting you know though.

**Comment by lukasbestle** [comment]
@bastianallgeier Why does the error occur in this case? Could this be abused by attackers?

**Comment by bastianallgeier** [comment]
@lukasbestle the router won't handle those brackets. It's the same error as if a file does not exist. I don't see a way this could be abused.

**Comment by lukasbestle** [comment]
You are right, I've verified that it's caused by the allowed characters in the `(:any)` route wildcard, which is defined to be:

```
a-z
A-Z
0-9
.-_%= +@()
```

If I manually add `[]` to this wildcard, the view is rendered as normal. So it's nothing serious, just a compatibility issue.

Given that the Panel applies `Str::slug()` to the filenames of all uploaded files, I think it's pretty clear that special characters (apart from the ones listed above) in manually uploaded filenames are currently not supported.

There are a few ways we could add support (extend the `(:any)` wildcard, apply URL escaping to the filename in the URL, switch to the `(:all)` wildcard). Supporting any character (including Unicode ones) would indeed be a nice enhancement. We had similar feedback a few times in the past and I can understand that applying `Str::slug()` is not always a good solution.

**Comment by distantnative** [comment]
Isn't the idea of `Str::slug()` that were left with a string that works in URLs? Given that our Panel URLs are based on file names too, I feel like sticking with `Str::slug()` makes a lot of sense. Question is whether that method needs to support more characters

**Comment by distantnative** [comment]
Isn't the idea of `Str::slug()` that were left with a string that works in URLs? Given that our Panel URLs are based on file names too, I feel like sticking with `Str::slug()` makes a lot of sense. Question is whether that method needs to support more characters

**Comment by lukasbestle** [comment]
TBH I feel like "characters that work in URLs" is no longer a thing. Browsers now consistently and transparently convert between percent-encoded URLs and Unicode IRIs when needed (meaning that even Unicode in links is converted to percent-encoding for the HTTP request and back to the human-readable form for display in the address bar).

So I wonder what speaks against supporting *any* character, even Unicode in page UIDs and filenames. The only truly "native" solution for us would be to use percent encoding for URLs throughout the system.

Nothing that we can migrate to quickly though. So maybe something for Nolt?

**Comment by distantnative** [comment]
Opened one: https://kirby.nolt.io/550
Feel free to add/improve the description.

And @MikeHarrison upvote please.
