### ISSUE TITLE
Only Kirby/Cms/Collection can be returned inside collection() (regression?)

### ISSUE THREAD

**Issue by tristantbg** [k-next/kirby#5169]
## Description
It is now impossible to return something else than a Kirby/Cms/Collection inside collection() helper.
https://github.com/getkirby/kirby/blob/282b1e25faa0bc24c903237a7484dc45fa475c36/config/helpers.php#L54

**Expected behavior**  
Before it could be anything, like a specific page, array, Kirby/Toolkit/Collection
This was very handy to prevent doing this in multiple controllers. Or maybe there is another helper I am not aware of ?

**Comment by bastianallgeier** [comment]
I think we overdid it here with type hinting. @distantnative @lukasbestle what are your thoughts?

**Comment by distantnative** [comment]
I can see Toolkit\Collection, but a single page returned from the collection helper?

**Comment by tristantbg** [comment]
> I can see Toolkit\Collection, but a single page returned from the collection helper?

Yes for example :

````
'projectsPage' => function ($site) {
  return $site->pages()->filterBy('intendedTemplate', 'projects')->first();
},
'projects' => function ($site) {
  if ($p = collection('projectsPage')) {
    return $p->children()->listed();
  } else {
    return false;
  }
},
'projects.all' => function ($site) {
  return collection('projects')->add(collection('journalProjects'));
},
'aboutPage' => function ($site) {
  return $site->pages()->filterBy('intendedTemplate', 'about')->first();
},
  ````

**Comment by tristantbg** [comment]
Since collection() can also be used inside a plugin, it would be great to extend a bit more the possibilities with this function. Or maybe create another one more generic ?

**Comment by distantnative** [comment]
I think your use cases would make much more sense as site methods (also possible via plug-in), but they don't really fit the collection helper

**Comment by tristantbg** [comment]
> I think your use cases would make much more sense as site methods (also possible via plug-in), but they don't really fit the collection helper

Ok thank you for clarifying this !
Then collection() should be only for a set of files/pages/array/collection (toolkit+cms) then ?

**Comment by lukasbestle** [comment]
I agree with Nico that the return value should be a collection. I'd be open to add support for `Toolkit\Collection`, but on the other hand I'm not sure if there is a use case where a Toolkit collection needs to be used instead of a CMS collection.

**Comment by tristantbg** [comment]
> I agree with Nico that the return value should be a collection. I'd be open to add support for `Toolkit\Collection`, but on the other hand I'm not sure if there is a use case where a Toolkit collection needs to be used instead of a CMS collection.

For this kind of purpose but maybe I can do it with Kirby/Cms/Collection instead ?

````
'categories.products' => function ($site) {
   return new Kirby\Toolkit\Collection(collection('products')->pluck('category', null, true));
},
````

**Comment by lukasbestle** [comment]
`Cms\Collection` extends `Toolkit\Collection`, so it can do everything `Toolkit\Collection` can plus a few extra things. So probably yes.

**Comment by tobiasfabian** [comment]
For the [Merx Starterkit](https://github.com/wagnerwagner/merx-starterkit) I have something like this (simplified).

```php
// collections/payment-methods.php
<?php
return function (): Kirby\Toolkit\Collection
{
    return new Kirby\Toolkit\Collection([
        'paypal' => [
            'label' => t('paymentMethod.paypal.label'),
            'submitText' => t('paymentMethod.paypal.submitText'),
        ],
        'credit-card' => [
            'label' => t('paymentMethod.creditCardSca.label'),
        ],
    ]);
};
```

```php
// snippets/payment-methods.php
<?php if (collection('payment-methods')->has('credit-card')): ?>
// do something
<?php endif ?>
```

When I change `Kirby\Toolkit\Collection` to `Kirby\Cms\Collection`, the if statement `(collection('payment-methods')->has('credit-card'))` won’t work like this, because `Kirby\Cms\Collection` won’t have keys (*paypal*, *credit-card*) and $collection->has() does look for keys.

The `__construct()` respectively the [set](https://github.com/getkirby/kirby/blob/3.9.4/src/Toolkit/Collection.php#L65) and [add](https://github.com/getkirby/kirby/blob/3.9.4/src/Cms/Collection.php#L64) methods work differently in Toolkit and Cms.

A solution would be something like this.

Add a an `id` to the collection’s items and search with `findBy` for the desired id.

```php
// collections/payment-methods.php
<?php
return function (): Kirby\Cms\Collection
{
    return new Kirby\Cms\Collection([
        [
            'id' => 'paypal'
            'label' => t('paymentMethod.paypal.label'),
            'submitText' => t('paymentMethod.paypal.submitText'),
        ],
        [
            'id' => 'credit-card'
            'label' => t('paymentMethod.creditCardSca.label'),
        ],
    ]);
};
```

```php
// snippets/payment-methods.php
<?php if (collection('payment-methods')->findBy('id', 'credit-card')): ?>
// do something
<?php endif ?>
```

I think it’s prettier to make use of the `has()` method (which is only possible with `Kirby\Toolkit\Collection` in my case). However, if you think it’s better to limit the return type to `Kirby\Cms\Collection` it wouldn’t be a big deal to change my code.

**Comment by lukasbestle** [comment]
I'd say that's convincing. At the moment I don't see a definite reason to limit to `Cms\Collection`, so supporting `Toolkit\Collection` is IMO fine.

**Comment by afbora** [comment]
@lukasbestle After the base collection change in helper, we need to update the type hints in `App:collection` and Collections class, right?

**Comment by lukasbestle** [comment]
@afbora Yes, I agree. If we do the change, we should do it throughout.

**Comment by afbora** [comment]
I got stuck. Because I knew that `Collections` only return a `Collection`. I realized that all kinds of data return. I've no idea about that 🤷‍♂️ 

> TypeError : Kirby\Cms\Collections::get(): Return value must be of type ?Kirby\Toolkit\Collection, string returned

https://github.com/getkirby/kirby/blob/282b1e25faa0bc24c903237a7484dc45fa475c36/tests/Cms/Collections/CollectionsTest.php#L30-L67

**Comment by distantnative** [comment]
Ok guess we did want Collections to allow returning different stuff than just a Collection. Although our docblocks suggest differently but tests and docblock contradict each other.

What do we want to go forward with?

**Comment by lukasbestle** [comment]
Hm, interesting. These tests were already in the very first commit to this repo in 2019 (slightly changed since, but already returning a string from a collection function). We also already had the `Collection` return type hint back then.

I still think that it does not make sense to return anything else than a collection from a collection function.

What about this:

- In 3.9.5, remove the forced `Cms\Collection` type hint and put it back into the docblock (fixing the regression we introduced lately). IMO the docblocks can already be changed to `Toolkit\Collection`.
- In v4, introduce a deprecation warning when anything else than a `Toolkit\Collection` is returned. At the same time remove the unit tests that violate that deprecation or replace them with suitable tests based on collections.
- In v5, add PHP type hints (breaking change).
