### ISSUE TITLE
[v4] Writer field: UUID links are removed in subfolder installations

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#5208]
## Description

Add a link to a page in writer using the link field, adds `<a>Text</a>` without href.

## Notes for later reference:

Happens because of "The URL points outside of the site index URL" check in `Dom::isAllowedUrl()`.

Possible solution: We do have the `allowedDomains` option already, but that of course only covers domains. We could make `allowHostRelativeUrls` with a default of `true`, but then if someone needs the protection, the writer field would again not work.

Discord discussion: https://discord.com/channels/525634039965679616/525637437494657024/1110583259919818935

**Comment by medienbaecker** [comment]
> Happens because of "The URL points outside of the site index URL" check in Dom::isAllowedUrl().

Maybe I'm the one who's confused but I think the `isAllowedUrl()` function is not the issue.

I believe the Writer field doesn't generate correct links for the files in the first place.
Instead of `example.com/subfolder/@/file/xyz` it's just `example.com/@/file/xyz`. This in turn does not pass the `isAllowedUrl()` check but that's expected.

You can reproduce this by adding a file link, right clicking on it and opening it in a new tab. After reloading the link is gone (or much rather an empty a tag).

**Comment by lukasbestle** [comment]
> I believe the Writer field doesn't generate correct links for the files in the first place.
Instead of `example.com/subfolder/@/file/xyz` it's just `example.com/@/file/xyz`. This in turn does not pass the isAllowedUrl() check but that's expected.

@medienbaecker When we tested this before we opened this issue, the writer field generated host-relative URLs (so `/@/file/xyz`). This is also the expected behavior, even in subfolder setups. If we included the name of the subfolder in that URL, the site would break when served in a different environment (with a different or without a subfolder). This is also the reason why the URLs are host-relative (to make them independent of the domain).
