### ISSUE TITLE
[v4] Smaller font size results in bad mobile experience for iOS users

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5395]
## Description
An old long-running issue with building websites is that input boxes have to be at least 16px large, or iOS Webkit will start to zoom in on clicking on any input box. As the new UI update switches all inputs to 14px (or 0.875rem), Safari will now zoom in on clicking on any input box, which is a very bad experience for mobile editors.

My preferred solution would be to not change the input font size, but I guess that's kinda given and not to be changed with your redesign. The input height is still the same, just the font size is smaller, and the spacing is larger.

[Example video](https://drive.google.com/file/d/1K-JZ3UP8-2kFbTjJHoXjQZJ27ID61tbL/view?usp=sharing)

## Your setup
**Kirby Version** 4.0.0-alpha.5

**Your system (please complete the following information)**
 - Device: iPhone 13 mini
 - OS: iOS
 - Browser: Safari

**Comment by bastianallgeier** [comment]
The decision to move to a smaller font size is based on the font sizes that we use for cards, cardlets etc and horizontal space for various narrow situations. We've been aware that we still need a solution for mobile, but I don't mind increasing the font size back to 16px there again. Everything breaks down to single column layouts on mobile anyway.

**Comment by tobimori** [comment]
> The decision to move to a smaller font size is based on the font sizes that we use for cards, cardlets etc and horizontal space for various narrow situations. 

Maybe it's just me, but I find some texts much harder to read in the new design, hence I'd prefer the old font size.

**Comment by bastianallgeier** [comment]
Do you have examples? The only places where we went for 14px instead of 16px are inputs and labels.

**Comment by tobimori** [comment]
> Do you have examples? The only places where we went for 14px instead of 16px are inputs and labels.

Must change: Help texts are too small for me, especially the decreased line height makes it hard to read, at least 13px (like in the old design) & 1.4-1.5 line height imo.

**Comment by iskrisis** [comment]
Besides the 16px iOS input. After developing on new panel for some time. I share what Tobi is saying. I would be quite bit worried that everyone is gonna go zoom 120% which will introduce the spacing issues again. I have pretty good eyes and it is bothering me too. And Tobi is like 16 if he can't see it who can.

Then again github has inputs with almost the same settings. So I guess its just contrast and me not being used to it.

**Comment by distantnative** [comment]
I think that's what I am a bit confused: why would a lot of people zoom on the Kirby Panel now when so many places around the web where people don't zoom also use 14px inputs?

**Comment by iskrisis** [comment]
Well that's kinda the mysterious hard thing about design isn't it?

**Comment by distantnative** [comment]
Maybe it's just "unfamiliarity".

**Comment by tobimori** [comment]
I think the spacing being larger makes the font feel smaller

**Comment by bastianallgeier** [comment]
I bet that we would get the reverse feedback if we let it stay at 14 px for a couple months and then bump up the font size. 

I think the criticism about contrast, the input zoom and also the tiny size of the help text is valid. But buttons, cards, cardlets, list items, menu items and more have been at 14px before and we didn't get a single complaint in all those years.

**Comment by iskrisis** [comment]
I don't think this belongs to the github technical issue so sorry I shouldn't have started. Please treat the design feedback as opinions/suggestions what do you take out of them is up to you. Any time i discuss design it seems like i am upsetting someone it's not at all my goal. Kirby panel doesn't get redesigned often and i am way more experienced designer then dev so am just excited to voice opinions. Ill try to limit it.

@tobimori i disagree - it might look smaller but it generally makes things more relaxed and seem bigger. For example compare github Comment button and kirby Save page button (where there is tighter x padding) but both have same fontsize.

@bastianallgeier i am not sure. It might. I took some time to let stuff sink in and i think there is still something about things feeling smaller. Probably some balancing of other stuff than fontsize. Nothing to be stressed about though. These things are hard and never really finished.

Sidenote don't forget devs probably dogfood and look at panel way more than you do and thus have different view of it. In a way ours (devs) nor yours opinion matter that much compared to users/editors. Like i said for them i think it's probably gonna look cool.

**Comment by bastianallgeier** [comment]
I think the problem here is that we are very close to design by committee when we openly discuss such topics. This is good on one hand because we have quite a few folks with a lot of design experience in our community. But it's also a bad thing because design by committee never really works and such discussions can become difficult quickly. 

Design is a way more emotional topic than coding would ever be. There are stronger opinions because the rules are a lot harder to define and agree on. When we work on design aspects of the panel, we already have hard discussions about details in the team. We spend a lot of time on those discussions and I think they are important. We just yesterday had a lengthy discussion about animations. We still know that the end result will always be a snapshot of what currently feels like the best possible approach for us. This snapshot often only lasts a few days until we get issue reports from you or we find issues ourselves. It's also always a compromise to a certain extend. A compromise between different design directions, accessibility considerations, technical limitations, etc. etc.

I'm very sure that the final release will have quite a few more visual changes in the next weeks. I'm not even 100% sure if we stick with the 14px. Right now I'm still happy with it and the general feedback seems to be positive. Let's let it sink in even some more. We still have a lot of work on the technical side to do for now and will come back to it a bit later.

**Comment by distantnative** [comment]
Do I understand it correctly, that the minimal fix needs to be to raise the font-size on small screens so iOS Webkit doesn't zoom?

**Comment by iskrisis** [comment]
> Do I understand it correctly, that the minimal fix needs to be to raise the font-size on small screens so iOS Webkit doesn't zoom?

Yes. Safari needs exactly 16px for inputs to not trigger zoom https://defensivecss.dev/tip/input-zoom-safari/

**Comment by distantnative** [comment]
Ok, so we just have to decide on a breakpoint to switch to 16px on smaller devices. Could make sense on the one when breaking to 1-column layouts.

**Comment by bastianallgeier** [comment]
Here's a first step to bring back the old help text size: https://github.com/getkirby/kirby/pull/5549
