### ISSUE TITLE
[v4 alpha.5] Descenders are cut off in page title in panel

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#5415]
## Description
In the new layout, the parts of the font which go under the baseline get cut off by the `overflow: hidden` style which is applied to the page title text.

**Expected behavior**  
All the font should be visible

**Screenshots**  
<img width="405" alt="image" src="https://github.com/getkirby/kirby/assets/6684137/cb716f22-f1aa-4a64-862c-62e684c5a5a1">
(notice the *g*)
## To reproduce
1. Have a page title with descenders. 
2. Open that page on Windows (I guess it's limited to Segoe UI)

## Your setup
**Kirby Version**  
4.0.0 alpha 5

**Your system**
 - Device: Windows PC
 - OS: Windows 11
 - Browser: Chrome 115

**Additional context**  
The rendered font is **Segoe UI Semibold**.
The page title text gets its `overflow: hidden` together with `text-overflow: ellipsis`, but since the text is able to wrap (i.e. it has no `white-space: nowrap`) the ellipsis is never actually applied, making the whole `overflow: hidden` kind of pointless.

**Comment by afbora** [comment]
https://github.com/getkirby/kirby/blob/4.0.0-alpha.5/panel/src/components/Text/Headline.vue#L87-L92

Shouldn't there be a line-height as the heading gets bigger (h6 to h1)? Here it is the opposite. When we increase `line-height`, value, this problem is fixed. But I don't understand the different situation in these codes. I guess to keep the height the same for different heading sizes.

**Comment by bastianallgeier** [comment]
@afbora bigger font sizes need reduced line heights to look visually fine and don't fall apart. I think we can fix this differently.
