### ISSUE TITLE
[v4] 'slugs' => 'de' broken

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#5423]
## Description
It seems that the config option `'slugs' => 'de'` is broken in 4.0.0-alpha.5. When I activate it and create a new page with the title "Über uns", the auto-created slug is "uber-uns".

**Expected behavior**  
I'd expect the slug to be "ueber-uns".

**Screenshots**  
![Screenshot 2023-07-28 at 16 27 56](https://github.com/getkirby/kirby/assets/60777/2818d6f1-99bd-414c-add2-bf4f6a71875f)

**Kirby Version**   
4.0.0-alpha.5

**Comment by afbora** [comment]
### Summary

This issue coming from following line:
https://github.com/getkirby/kirby/blob/4.0.0-alpha.5/panel/src/components/Forms/Input/SlugInput.vue#L54

Because `this.$language` always return default object with new language module:
https://github.com/getkirby/kirby/blob/4.0.0-alpha.5/panel/src/panel/language.js

### Solution idea

`this.$language` should be return `null` instead default object
