### ISSUE TITLE
[v4] header buttons jump unexpectedly when save button appears

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#5438]
https://github.com/getkirby/kirby/assets/60777/4a0b25c2-4db4-4388-9822-465953f49ba8

I'm editing something and the header-buttons suddenly move into a new row because the save button appears.
I'm not sure if there is a good solution for this. At least not an elegant css-only one. I think visually the best would be to already move the buttons below the title. To reserve the space.

4.0.0-alpha.5

**Comment by distantnative** [comment]
It's a bit of a guessing game: how much space do we need to reserve for the save/reset buttons depending on the different languages? And what about the lock/unlock state?

**Comment by distantnative** [comment]
@bastianallgeier Do you have an idea for this? Mine (max-width for title, flex-basis for buttons) all result in other situations where it's not great. So seems like we would need to pick between bad options.

**Comment by distantnative** [comment]
One more idea: reserving a certain space for the buttons but not letting the header flex-wrap, so the buttons always stay in place, though the title wraps differently when the buttons grow out of their min-width. So there still can be some jumping:

<img width="1104" alt="Screenshot 2023-09-09 at 12 33 10" src="https://github.com/getkirby/kirby/assets/3788865/b8d8fefa-13f6-4ebe-999a-ed504ef716d1">
<img width="1110" alt="Screenshot 2023-09-09 at 12 33 15" src="https://github.com/getkirby/kirby/assets/3788865/2b1aab5a-59c4-4a1f-b10a-7af4dd9a0561">

**Comment by lukasbestle** [comment]
I saw a [suggestion in Discord](https://discord.com/channels/525634039965679616/1151522529664585830/1151522931399204975) that inspired me. What if:

1. We swap the positions of the `FormButtons` and the other header buttons so that the `FormButtons` are always on the left.
2. Then, we don't `display: none` the `FormButtons` when there are no unsaved changes. Instead, we `opacity: 0; pointer-events: none` them and hide them from assistive technology by making them a `span` instead of a `button`.
3. Result: The `FormButtons` will take up the same amount of room no matter if they are visible or not. This way, they always reserve just the space they need.

**Comment by distantnative** [comment]
This will be solved with (likely) v5 as changes there will have the form buttons/controls be displayed all the time. Closing this issue as any other fix before that isn't warranted the effort at this moment.
