### ISSUE TITLE
[v4] Layout Toolbar Overflow

### ISSUE THREAD

**Issue by lukaskleinschmidt** [k-next/kirby#5449]
## Description
There seems to be an overflow issue in narrow layouts.

![grafik](https://github.com/getkirby/kirby/assets/10027897/22e1392e-e8e4-4f28-ad87-b0b0d52ca508)

## Your setup
4.0.0-alpha.6

**Your system (please complete the following information)**
 - Browser: Firefox
 - Version: 117

**Comment by distantnative** [comment]
I'm afraid this might need a JS solution:
1. measure available width (max. width of field)
2. measure space nodes and marks would take
3. move marks into a "..." dropdown as long as (2) is larger than (1)

**Comment by bastianallgeier** [comment]
One part is already fixed. The layout box is no longer cutting off the toolbar. But the toolbar is still not at full width and will have a scrollbar even if there's enough space. I think this is related to the new positioning logic.

**Comment by distantnative** [comment]
@bastianallgeier Three things:
1. `.k-writer-toolbar[data-inline="true"]` should have a `max-width: none;` added to be full-width without scrollbar
2. The positioning logic still fails: it first tries to correct overflow to the left, then to the right. If the toolbar is larger than the container, it first shifts it to the right, then back to the left and will have an overflow. This is because we can only assess the overflow/offset in relation to the container - not the full window (where it might have more space to either side).
3. With `position: absolute` it'll be very hard to break out of the editor itself. If we want to use the space around the editor itself for the toolbar to overlay, we'll need to move to `position: fixed`
