### ISSUE TITLE
Textarea field - CSS styles inside <style> tag are mistakenly processed as markdown text after the first code block

### ISSUE THREAD

**Issue by miragecraft** [k-next/kirby#5478]
## Description
I should be able to embed CSS <style> tags into the textarea field, but the output is mangled after the first code block.

It looks like any CSS styles after the first code block is being treated as regular markdown text, as the code is wrapped with `<p>` tag and interspersed with `<br />` tags. 

```html
<style>
.red {
  color:red;
}

.blue {
  color:blue;
}
</style>
```

Became the following in the browser

```html
<style>
.red {
  color:red;
}
<p>.blue {<br />
color:blue;<br />
}</p>
</style>
```

**Expected behavior**  
All CSS style inside the <style> tag should be left alone.

**Screenshots**  

![image](https://github.com/getkirby/kirby/assets/1615599/6b43cb77-45bc-4e69-8d23-ac96a03a717a)

## To reproduce

Enter the following into the textarea field

```markdown

Some regular *markdown* text.

<style>
.red {
  color:red;
}

.blue {
  color:blue;
}
</style>

<span class="red">Some red text.</span>

<span class="blue">Some blue text.</span>
```

Save and view the output in the browser.

## Your setup
**Kirby Version**  
3.9.6.1

**Comment by distantnative** [comment]
How do you output the field in your template?

**Comment by miragecraft** [comment]
> How do you output the field in your template?

Using `<?= $page->text()->kirbytext() ?>`

**Comment by miragecraft** [comment]
@distantnative do you still need more information?

**Comment by rasteiner** [comment]
The problem here is the library which Kirby uses to parse markdown: Parsedown.

Kirby is using the latest tagged 1.x version: 1.8.0-beta-7, as you can see [here (click "run" on the bottom right)](https://phpsandbox.io/e/x/zy4vu?layout=EditorPreview&defaultPath=%2F&theme=dark&showExplorer=no&openedFiles=) it's Parsedown that doesn't work as expected.

Switching to the next version (which also is in eternal "beta"), 2.0.0-beta1, would fix your issue, but would also introduce more breaking changes as it no longer provides the "setBreaksEnabled" function. See [here](https://phpsandbox.io/e/x/wxpv8?layout=EditorPreview&defaultPath=%2F&theme=dark&showExplorer=no&openedFiles=) the "missing" `<br>` between the normal text lines. 

Version 2 is formally correct in not adding the `<br>`, as per Markdown spec you need to end a line with 2 empty spaces to get a line break, but I fear that most kirby users wouldn't understand such a rule. So Kirby is a between a rock and a hard place with this issue: it can't really be solved without angering someone. 

I guess one option for you would be to swap out the markdown parser, via the "markdown core component" interface: https://getkirby.com/docs/reference/plugins/components/markdown

**Comment by miragecraft** [comment]
> Version 2 is formally correct in not adding the `<br>`, as per Markdown spec you need to end a line with 2 empty spaces to get a line break, but I fear that most kirby users wouldn't understand such a rule. So Kirby is a between a rock and a hard place with this issue: it can't really be solved without angering someone.

According to [CommonMark Spec](https://spec.commonmark.org/0.30/#soft-line-breaks) soft linebreaks handling is up to the renderer:

> A renderer may also provide an option to render soft line breaks as hard line breaks.

So all Kirby needs to do is add a post-processing step to convert newlines into `<br>` tags.

I don't see how this is an obstacle to moving to version 2.

I feel the best way forward is for Kirby to move to Parsedown v2, but I'll create an issue over at the Parsedown project page.

**Comment by distantnative** [comment]
From our experience, switching those parsers - whether markdown or yaml - is always a huge risk of breaking people's existing sites. 

But I haven't had a look at this in a longer time, so not sure how big the risk is for v2.

**Comment by lukasbestle** [comment]
I agree with Nico. We want to switch to a more solid parser in the long run, however it's a big task. And TBH Parsedown v2 is not really an option here as there's no stable release and future maintenance doesn't seem likely (as is already the case with Parsedown v1).

@miragecraft To get back to your original issue: There's a workaround: You can remove the newline between your style rules. To Parsedown it is then a single paragraph and the line breaks are no longer inserted:

```html
<style>
.red {
  color:red;
}
.blue {
  color:blue;
}
</style>
```

I'd close this issue as we cannot solve it directly, only with a general change of the Markdown parsing library.

**Comment by miragecraft** [comment]
> @miragecraft To get back to your original issue: There's a workaround: You can remove the newline between your style rules. 

Wow thanks! In hindsight it was obvious, somehow it didn't come across my mind to try that.

> I agree with Nico. We want to switch to a more solid parser in the long run, however it's a big task. And TBH Parsedown v2 is not really an option here as there's no stable release and future maintenance doesn't seem likely (as is already the case with Parsedown v1).

Statamic uses the [CommonMark parser](https://github.com/thephpleague/commonmark), which seems to be the most active project.

> I'd close this issue as we cannot solve it directly, only with a general change of the Markdown parsing library.

Got it, closing now.
