### ISSUE TITLE
Writer Toolbar un-reachable for fields with very long copy

### ISSUE THREAD

**Issue by ovenum** [k-next/kirby#6021]
## Description
When the Writer Field toolbar is not inline, the toolbar will become unreachable in long textfields that are taler than the screen height.

**Expected behavior**  
The Toolbar to be always reachable/ usable

## To reproduce
Create a Writer Field with 
```yaml
toolbar:
  inline: false
```

Add looong copy text so that the field height is higher than the screen height. Scroll down to edit text at the bottom of the field. The writer toolbar will not be visible anymore.

## Your setup
**Kirby Version**  
4.0

**Comment by distantnative** [comment]
It should be sticky when the field has focus. Will need to check this later, if a general problem or something more specific in your setup.

**Comment by ovenum** [comment]
Thanks for looking into this. Just re-checked the issue.
The writer field is contained inside a blocks field.  Focusing the writer field and scrolling will not make the toolbar sticky. I also checked by hiding the k-page-view-header component with dev-tools.

**Comment by distantnative** [comment]
Are you sure about the last part?
Can reproduce the general issue, but when I lower the opacity of the page header, I can see the toolbar hiding beneath:
<img width="1123" alt="Screenshot 2023-11-29 at 23 00 50" src="https://github.com/getkirby/kirby/assets/3788865/6eb28930-825c-4403-8b8b-92413e925993">

Note: the issue seems to be that also for `inline: false` there are top/left style values set on the toolbar, overwriting the sticky top offset.

**Comment by ovenum** [comment]
Sorry Nico! Should have supplied a proper reproducible example when creating the issue.

The toolbar will become sticky when the writer field is inside the first block (hidden behind the _k-page-view-header_). 
It will not become sticky when it’s not inside the first block.

Hope it’s reproducible now.

**UPDATE**
It’s exactly as you described. I mixed up Block Field focus and Writer Field focus!
