### ISSUE TITLE
Date field: focus issue when multiple usage in same page

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#6071]
## Description

https://github.com/getkirby/kirby/assets/3393422/d010157f-101f-405b-9de4-40590e8972fd

## Your setup
**Kirby Version**  
4.0.1

**Comment by gbdesign2023** [comment]
In this case, I would like to add that the date field remains open if a date has been selected here. Is it an error that it does not close? An open date field after the selection makes no sense in my opinion.

**Comment by afbora** [comment]
For example case: I may have opened the calendar to choose a date for first date field and gave up. In this case it is supposed to close calendar and focus on the other clicked second date field.

**Comment by distantnative** [comment]
I think what @afbora is describing is due to the calendar dropdown being a `dialog` document - in that case the first click only cancels the dialog and the second one needs to be used to focus the other input. So no idea if we could fix/improve this. Maybe @bastianallgeier has an idea.

But I thin @gbdesign2023 is right about closing on selection, that should happen.

**Comment by bastianallgeier** [comment]
I don't really think that there's a valid workaround for this. It's the same when you want to click directly on any other button or link. The backdrop catches the click first. We probably want to switch to the new popover api at some point for the dropdowns, but that still seems to be too far away. 

About the selection: I think we decided to keep it open in an earlier issue/PR because it feels more intuitive to navigate around and maybe switch between dates. I would vote to close this issue.
