### ISSUE TITLE
[4.1] Investigate color field dynamic options

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#6101]
Initial discussion: https://github.com/getkirby/kirby/pull/6056

- [ ] Ensure new dynamic options work properly
- [ ] Contemplate if we can switch the key-value order

**Comment by distantnative** [comment]
It seems very hard to get blueprint, dynamic etc. options consistent with the reversed key-value notation.

@lukasbestle @bastianallgeier do you see any chance to undo our 4.0 mistake and flip the color field notation to be in line with other options?

**Comment by bastianallgeier** [comment]
Could we maybe have some sort of polyfill for the "mistake" in the field and check for color values in the keys and then convert it to our regular option syntax?

**Comment by lukasbestle** [comment]
Yeah, had the same thought. If the first key is a valid color, we can assume that the "new way" of keys being the color is used. Otherwise we still use the value as the color but deprecate that (maybe with a warning in v5 and removed in v6).

I think that should be pretty safe as using a valid color code as the label should be quite rare.

There are then basically three cases:

1. Just an array of color values (detected by integer keys)
2. Label as key, color as value (deprecated)
3. Color as key, label as value (new default and documented)
