### ISSUE TITLE
can't `parse_url()` for creating URIs that use pagination logic

### ISSUE THREAD

**Issue by samyouel** [k-next/kirby#6331]
## Description
I've been following the [cookbook to setup 'Load More' Functionality with Kirby Pagination](https://getkirby.com/docs/cookbook/templating/ajax-load-more).

The model named 'Rewards' is using virtual pages, to fetch the children of the model from an API.

I'm using [page cache](https://getkirby.com/docs/guide/cache) to cache the content of the page. 
During the `function children()`, when I call the children of the model over API, I clear the page cache by using `kirby()->cache('pages')->remove('rewards.html')` in certain conditions.

This accessing the page cache is not working once I click the 'Load More' Button, that calls the paginated children from the `rewards.json.php`.

**Expected behavior**  

The 'Load More' Button should fetch the children in the same way and display them, as an initial page load should be able to as well.

**Actual behaviour**

When I use the AJAX 'Load More' Button as outlined in the cookbook, the request fails upon the moment of accessing the page cache.

I've traced it down to `kirby/src/Http/Uri.php:91`, during accessing the page cache, it tries to build a URI, but somehow the `parse_url()` function from php can't build a url from the pagination url `"/rewards.json/page:2"` that is being sent with the call.
I guess because of the colon `:`. 

## Stack trace

```bash
"NOTICE: PHP message: Whoops\Exception\ErrorException: Automatic conversion of false to array is deprecated in /var/www/html/kirby/src/Http/Uri.php:92"
"Stack trace:"
"#0 /var/www/html/kirby/src/Http/Uri.php(92): Whoops\Run->handleError(8192, 'Automatic conve...', '/var/www/html/k...', 92)"
"#1 /var/www/html/kirby/src/Http/Uri.php(214): Kirby\Http\Uri->__construct(Array, Array)"
"#2 /var/www/html/kirby/src/Cms/App.php(1662): Kirby\Http\Uri::current(Array)"
"#3 /var/www/html/kirby/src/Cms/System.php(159): Kirby\Cms\App->url('index', true)"
"#4 /var/www/html/kirby/src/Cms/AppCaches.php(80): Kirby\Cms\System->indexUrl()"
"#5 /var/www/html/kirby/src/Cms/AppCaches.php(32): Kirby\Cms\App->cacheOptions('pages')"
"#6 /var/www/html/site/models/rewards.php(29): Kirby\Cms\App->cache('pages')"
"#7 /var/www/html/site/controllers/rewards.json.php(6): RewardsPage->children()"
"#8 [internal function]: Kirby\Cms\App->{closure}(Object(RewardsPage))"
"#9 /var/www/html/kirby/src/Toolkit/Controller.php(60): Closure->call(Object(Kirby\Cms\App), page..."
```

## To reproduce

1. try `parse_url('/rewards.json/page:2')` that is used in the mentioned file
2. it will give you false, because the URL is malformed.

_-> Is there something wrong with this URI Constructor?_

## Your setup
**Kirby Version**  
getkirby/cms (4.1.1) composer install

**Comment by distantnative** [comment]
## Summary
- To get the proper cache options, Kirby tries to get the index url
- For that it wants to create the current Uri object via `Uri::current()`
- That takes the request url as main parameter for the constructor https://github.com/getkirby/kirby/blob/main/src/Http/Uri.php#L214
- Then in the constructor `parse_url` fails as it cannot handle the parameter notation in the URL https://github.com/getkirby/kirby/blob/main/src/Http/Uri.php#L91
- And the Kirby crashes because in subsequent lines we assume that `$props` always is an array, while now it is `false`


Pinging @bastianallgeier @lukasbestle for ideas as you have a better insight on the Http classes, I think.

**Comment by lukasbestle** [comment]
Am I correct that this only happens if Kirby's `url` option was configured without a host (e.g. as `'url' => '/'`)?

But the underlying bug seems to be in `Uri::current()` or actually in the `Uri` constructor. Maybe we could solve it there by adding a fake host for non-absolute URLs and removing the injected data from the array that `parse_url()` returns again. We do a similar thing in the `Environment` class:

https://github.com/getkirby/kirby/blob/6b7ac66c55ecac20d6b580ef01a667d1806d5c72/src/Http/Environment.php#L605-L609

**Comment by distantnative** [comment]
Those lines form the Environment class sound like exactly what's needed here as well.

**Comment by jensscherbl** [comment]
This sounds kinda familiar. Not sure if it’s really helpful here, but I fixed a similar issue in the library that I use for my HTML minification plugin a while ago. See https://github.com/hexydec/htmldoc/pull/8

> Am I correct that this only happens if Kirby's url option was configured without a host (e.g. as 'url' => '/')?

Exactly. As noted on [php.net](https://www.php.net/manual/en/function.parse-url.php#refsect1-function.parse-url-notes) regarding `parse_url()`:

> This function may not give correct results for relative or invalid URLs [...]

and

> This function is intended specifically for the purpose of parsing URLs and not URIs.
