### ISSUE TITLE
`file.create:before` hook: allow to modify `$file` object

### ISSUE THREAD

**Issue by silllli** [k-next/kirby#6460]
## Description
I want to add additional data to an uploaded file in the `file.create:before` hook. (In my case: the original filename before it gets sanitized.) The hook is called but the data is not added to the file metadata.

```php
Kirby::plugin('sl/sl-plugin', [
  'hooks' => [
    'file.create:before' => function (
      Kirby\Cms\File $file,
      Kirby\Filesystem\File $upload
    ) {
      $file->update(['test' => 'test']);
    }
  ]
]);
```

**Expected behavior**  
The data to be updated and saved.

## To reproduce
1. Add a `file.create:before` hook
2. Update the `$file` in the hook
3. Upload a file
4. Check the file’s metadata

## Your setup
**Kirby Version**  
4.2.0

**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: macOS 14.5
 - Browser: Safari
 - Version: 17.5

**Comment by distantnative** [comment]
@silllli have you tried it with `file.create:after`?

**Comment by silllli** [comment]
Yes, there it works. But in the `after` hook the original file (passed as `$upload` in the `before` hook) is not available.

I could imagine that this is technically not possible (since we are in the **before** hook, so there is no actual file to `update()` yet). But then why pass the `$file` object to the hook?

Also, using the `file.create:before` hook to save things like the filename to the file metadata was suggested in the forum in several thread so I expected it to work.

**Comment by distantnative** [comment]
But in the after hook the original file should now be the actual file, shouldn't it? Or what else are you getting from `$upload`?

The problem here is that our objects (like `$file`) are immutable. So `$file->update()` does not change the file object, but rather creates a new one with the modified content. These hook types are though only triggers. So what happens in the hook is also not passed back to the general script. And thus the script continues with the file object as it was passed into the hook. In the after hook it's less apparent as there it also writes the new content to the now existing content file, so on any new request that content gets actually read.

It's an issue of the immutability of our objects. We will have to look into if we can change the hooks to return something without being a huge breaking change. But if the after hook works for you in the meantime, I would go with that.

**Comment by silllli** [comment]
> But in the after hook the original file should now be the actual file, shouldn't it? Or what else are you getting from `$upload`?

I am looking at ways to adjust the filename sanitization done by Kirby (mostly allowing uppercase letters). The Vue parts worked well, but adjusting the server-side sanitization is a lot more tricky. I found a solution that overwrites parts of the `File` class in a plugin. That needs some code copying from and fiddling with the Kirby core—so it’s anything but future-proof.

I thought saving the original filename in the `before` hook and then reapplying (with custom sanitization) it in the `after` hook would be a cleaner and more future-proof way of handling this. In the `after` hook, the filename was already sanitized and there is no way of accessing the original anymore.

Thank you for the quick replies!

**Comment by bastianallgeier** [comment]
Will be fixed in v5
