### ISSUE TITLE
Link dialog: The request to `tree/parents` failed

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#6627]
<img width="572" alt="Screenshot 2024-08-17 at 7 01 11 PM" src="https://github.com/user-attachments/assets/f319bd5c-cb3d-4bca-96c1-0ee1a14203be">

The the sandbox…
1. Go to writer field page
2. Type in some text, use the link dialog to select the `Home` page, save
3. Reload
4. Select the linked word and open the link dialog
5. See the error message

**Comment by tobimori** [comment]
Also happens with link field inside e.g. a structure.

**Comment by afbora** [comment]
## Summary

When no parents found, response is array, array is empty and we have empty check:
https://github.com/getkirby/kirby/blob/4.4.0-rc.1/src/Panel/Json.php#L78-L80

### Possible solutions
- Put `site/tree/parents` request in vue component into try/catch block
- Return a multidimensional array instead of flat array.

````php
return [
  'data' => $parents
];
````

**Comment by distantnative** [comment]
@afbora Makes sense, thanks for debugging. I think the 2nd solution sounds like the best way with our API.
