### ISSUE TITLE
`Please enter a valid role` issue on installation

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#6763]
Getting `Please enter a valid role` error when creating first account on installation in `v5/develop` branch.

**Comment by bastianallgeier** [comment]
@distantnative that's probably related to the role refactoring, right? @afbora could you check if the same problem also happens on develop-minor if you create a new account?

**Comment by distantnative** [comment]
https://github.com/getkirby/kirby/blob/develop-minor/src/Cms/UserRules.php#L210-L218

I think the cause is the following:
- At installation, `$currentUser` does not exist
- `$kirby->roles()->canBeCreated()` doesn't yield any roles
- `in_array($role, [null, 'default', 'nobody'])` is also false cause installation tries to create a user with role `admin`

**Comment by distantnative** [comment]
We could extend this: https://github.com/getkirby/kirby/blob/develop-minor/src/Cms/UserRules.php#L194

With `$user->kirby()->users()->count() === 0`.

Basically skipping the rest below if it's the first user.

**Comment by distantnative** [comment]
@afbora would you have time to create a fix/PR for this?
