### ISSUE TITLE
[v5] Plugin translation not applied in backend

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#6810]
I encountered a weird regression in Retour:

Translation that I apply in the backend (via `I18n::translate`) are not translated correctly anymore;

v4:
<img width="349" alt="Screenshot 2024-11-23 at 09 42 13" src="https://github.com/user-attachments/assets/88e9197b-8726-4e56-9f3f-ad217d9d0d94">
<img width="357" alt="Screenshot 2024-11-23 at 09 42 18" src="https://github.com/user-attachments/assets/98548f9b-90ca-4a9b-9d68-9363003a9e68">

v5:
<img width="262" alt="Screenshot 2024-11-23 at 09 42 46" src="https://github.com/user-attachments/assets/34b47d5c-8647-49e2-aa09-580a4c65496b">
<img width="328" alt="Screenshot 2024-11-23 at 09 42 50" src="https://github.com/user-attachments/assets/5148ee06-8354-4578-b67c-ed12dde170fb">

Interestingly, translation that are resolved in the frontend (`{{ $t() }}`) seem to work/unaffected.

**Comment by bnomei** [comment]
I encountered a similar issue when running commands. the license label build failed when retrieving `license.status.active.label` because the translation array for `en` local is still empty.

As far as I can tell from debugging the call stack the needed `AppTranslations` trait defining the i18n via closure has not been called yet when kirby encounters the `Kirby::plugin()` from within the plugins `index.php` file.

https://github.com/getkirby/kirby/blob/6adc851f1bd7de37933185594622bcc526f518d4/src/Cms/App.php#L141

**Comment by distantnative** [comment]
@bnomei how do you use it in your plugin?

**Comment by bnomei** [comment]
in calling a command from the cli is how i encountered the issue. you should be able to replicate it.

https://github.com/bnomei/kirby3-storybook/blob/main/commands/watch.php
